"""그림 주문서 「다시 그리기」 34칸 (사용자가 주문서에서 체크한 롬 칸, 2026-10-02)
 no: 지금 롬 칸 번호, id: digimon.net 문서 이름(공식 그림 주소), lcd: 위키몬 LCD 도트 (없으면 '')
 tones·keep·not_ 은 specs.py 와 같은 뜻. 주문문은 gen_order.py 의 sketch_prompt / front_prompt 로 만든다."""

W = 'https://wikimon.net/images/'


def d(no, id, ko, en, grade, lcd, white, light, dark, black, keep, not_=()):
    return dict(no=no, id=id, ko=ko, en=en, grade=grade, lcd=(W + lcd) if lcd else '',
                tones=dict(white=white, light=light, dark=dark, black=black), keep=list(keep), not_=list(not_) or ['Do not add features from other monsters.'],
                pal=PAL.get(id))


# 롬에 넣을 때 입힐 몸 색 두 개 (밝은·어두운). 받은 그림이 생긴 종부터 채움
PAL = {'piemon': ((216, 200, 160), (88, 64, 112)), 'meramon': ((248, 168, 72), (200, 48, 32)), 'omegamon': ((216, 216, 224), (184, 48, 48)),
       'imperialdramondragonmode': ((88, 88, 104), (200, 48, 48)), 'diablomon': ((160, 160, 176), (176, 40, 48)),
       'gekomon': ((120, 184, 96), (216, 168, 64)), 'rukamon': ((120, 176, 224), (48, 80, 144)),
       'picodevimon': ((136, 120, 160), (56, 40, 72)), 'lighdramon': ((112, 120, 152), (40, 40, 56)),
       'kabuterimon': ((104, 152, 224), (40, 64, 136)), 'wargreymon': ((240, 192, 96), (200, 96, 40)),
       'garurumon': ((152, 192, 240), (48, 80, 160)), 'archnemon': ((216, 208, 200), (96, 40, 56)),
       'chibimon': ((120, 160, 232), (40, 72, 160)), 'minomon': ((168, 200, 96), (96, 120, 56)),
       'pagumon': ((176, 168, 200), (88, 72, 120)), 'poromon': ((240, 152, 176), (200, 64, 96)),
       'metalgarurumon': ((176, 200, 232), (224, 168, 40))}   # 어두운 색 = 노란 날개 칼날·미사일 (사용자 2026-10-04)


R = [
 d(4, 'agumon', '아구몬', 'Agumon', '성장기', '2/28/Agumon_vpet_dv.gif', 'claws, teeth', 'orange-yellow skin', 'belly shading, the three-clawed feet', 'eyes',
   ['A small yellow-orange dinosaur standing upright on two legs.', 'Big green eyes, a wide mouth with small teeth.', 'Three sharp claws on each hand.', 'A short thick tail.'],
   ['No wings, no horns.']),
 d(6, 'wargreymon', '워그레이몬', 'WarGreymon', '궁극체', '1/1b/Wargreymon_vpet_dw.gif', 'metal highlights', 'orange skin, golden armor', 'the round shield on the back, gauntlets', 'eyes',
   ['A humanoid dragon warrior in golden armor with a horned helmet.', 'Huge metal gauntlets with three long claws on BOTH arms.', 'A big round shield carried on the back.', 'Orange hair flowing from the back of the helmet.']),
 d(7, 'gabumon', '파피몬', 'Gabumon', '성장기', '7/75/Gabumon_vpet_dv.gif', 'belly fur, the horn', 'yellow skin', 'blue-and-white striped fur pelt covering head and back', 'eyes, claws',
   ['A small yellow reptile wearing a wolf-fur pelt over its head and back.', 'One horn on the forehead of the pelt.', 'Stands on two legs, short tail.']),
 d(8, 'garurumon', '가루몬', 'Garurumon', '성숙기', 'f/ff/Garurumon_vpet_dv.gif', 'white fur', 'light blue fur', 'dark blue stripes', 'eyes, claws',
   ['A big four-legged wolf with sharp fangs.', 'Blue and white striped fur.', 'A horn on the forehead.', 'A long bushy tail.']),
 d(9, 'metalgarurumon', '메탈가루몬', 'MetalGarurumon', '궁극체', '2/29/Metalgarurumon_vpet_dw.gif', 'metal highlights', 'silver-blue metal body', 'yellow wings and missile pods', 'eyes',
   ['A four-legged metal wolf.', 'Metal wings on the back.', 'Missile pods and blades on the shoulders and legs.']),
 d(10, 'kunemon', '쿠네몬', 'Kunemon', '성장기', 'e/ed/Kunemon_vpet_dv.gif', 'belly', 'yellow body', 'black stripes, red-tipped antenna', 'eyes',
   ['A small caterpillar larva with black and yellow stripes.', 'One lightning-bolt antenna on the head.', 'A long segmented body.']),
 d(11, 'flymon', '플라이몬', 'Flymon', '성숙기', '0/0f/Flymon_vpet_dm.gif', 'wing highlights', 'orange-yellow body', 'black stripes, wings', 'eyes, stinger',
   ['A giant hornet with a big striped abdomen and stinger.', 'Four wings.', 'A furry mane around the neck.']),
 d(12, 'okuwamon', '오쿠와몬', 'Okuwamon', '완전체', 'a/a6/Okuwamon_vpet_dpc.gif', 'pincer edges', 'red-black shell', 'joints, wing membranes', 'eyes',
   ['A giant black stag beetle with TWO pairs of huge pincers.', 'Six arms.', 'Insect wings on the back.']),
 d(14, 'snimon', '스나이몬', 'Snimon', '성숙기', '6/6f/Snimon_vpet_d3.gif', 'scythe edges', 'green body', 'wings, joints', 'eyes',
   ['A green praying mantis.', 'Two big scythe blades for arms.', 'Thin wings on the back.']),
 d(15, 'archnemon', '아라크네몬', 'Arukenimon', '완전체', '', 'face skin', 'gray-white hair', 'spider legs and body', 'eyes',
   ['A spider woman: a human upper body on a big spider body.', 'Long white hair.', 'Eight spider legs.']),
 d(16, 'piyomon', '피요몬', 'Biyomon', '성장기', 'b/b5/Piyomon_vpet_dv.gif', 'belly', 'pink feathers', 'the feather tuft on the head, wing tips', 'eyes, claws',
   ['A small pink bird standing on two legs.', 'Wings used like arms.', 'A tuft of feathers on top of the head, a metal ring on one leg.']),
 d(25, 'mamemon', '콩알몬', 'Mamemon', '완전체', '2/20/Mamemon_vpet_dm.gif', 'eye shine', 'green round body', 'big brass knuckle gloves', 'eyes',
   ['A tiny round green ball creature.', 'Two huge metal boxing gloves (brass knuckles).', 'Short legs.']),
 d(27, 'drimogemon', '두리몬', 'Drimogemon', '성숙기', '4/4d/Drimogemon_vpet_dm.gif', 'drill highlights', 'brown fur', 'the big drill on the nose', 'eyes, claws',
   ['A big brown mole on all fours.', 'A large drill on its nose.', 'Big digging claws.']),
 d(28, 'digmon', '디그몬', 'Digmon', '아머체', '4/47/Digmon_vpet_dw.gif', 'drill highlights', 'yellow armor', 'the drills on nose and hands', 'eyes',
   ['A yellow armored insect.', 'A big drill on the nose and drills on the hands.', 'Stands on two legs.']),
 d(35, 'tailmon', '가트몬', 'Gatomon', '성숙기', '8/80/Tailmon_vpet_dv.gif', 'white fur', 'yellow gloves', 'tail stripes, ear insides', 'eyes',
   ['A small white cat standing on two legs.', 'Big yellow gloves with claws.', 'A long striped tail with a holy ring on it.']),
 d(41, 'picodevimon', '피코데블몬', 'DemiDevimon', '성장기', '4/4b/Picodevimon_vpet_dv.gif', 'mask, eye whites', 'dark gray body', 'bat wings', 'eyes, claws',
   ['A small black bat-like imp: a round body with big bat wings.', 'A bone mask with big eyes.', 'Small clawed feet.']),
 d(42, 'piemon', '피에몬', 'Piemon', '궁극체', 'c/c9/Piemon_vpet_dv.gif', 'mask, gloves', 'clown suit', 'cape, swords on the back', 'eyes',
   ['A clown magician in a mask.', 'A long cape.', 'Several swords on the back.', 'Seam lines on the costume are CLOTHING SEAMS of the outfit (not stitches on skin).']),
 d(43, 'tentomon', '텐타몬', 'Tentomon', '성장기', '6/6e/Tentomon_vpet_dv.gif', 'eye shine', 'red shell', 'belly, legs, claws', 'eyes',
   ['A small red ladybug-like insect.', 'Big green eyes.', 'Six legs, stands on the back pair.']),
 d(44, 'kabuterimon', '캅테리몬', 'Kabuterimon', '성숙기', '6/6f/Kabuterimon_vpet_dv.gif', 'horn highlights', 'blue shell', 'four arms, wings', 'eyes',
   ['A giant blue beetle with one big horn.', 'Four arms.', 'Insect wings.']),
 d(74, 'gottsumon', '울퉁몬', 'Gotsumon', '성장기', '4/4f/Gottsumon_vpet_dpc.gif', 'highlights', 'gray rock body', 'cracks and shading', 'eyes',
   ['A small creature made of rocks.', 'A rocky head with angry eyes.', 'Stubby rock arms and legs.']),
 d(93, 'devimon', '데블몬', 'Devimon', '성숙기', 'd/d3/Devimon_vpet_dv.gif', 'eye whites, belt buckle', 'dark gray body', 'bat wings', 'eyes, claws',
   ['A tall black devil.', 'Big bat wings.', 'Very long arms with claws.', 'Two horns on the head.']),
 d(111, 'hanumon', '에이프몬', 'Hanumon', '성숙기', '1/1c/Hanumon_vpet_d3.gif', 'white fur', 'brown fur', 'bone club, belts', 'eyes',
   ['A white ape warrior.', 'A bone club in hand.', 'Stands on two legs.']),
 d(112, 'mammon', '맘몬', 'Mammon', '완전체', 'a/a8/Mammon_vpet_dv.gif', 'tusks', 'brown fur', 'dark fur on the back', 'eyes',
   ['A huge woolly mammoth on four legs.', 'Two long curved tusks.', 'A long trunk.']),
 d(116, 'gomamon', '쉬라몬', 'Gomamon', '성장기', '4/4b/Gomamon_vpet_dv.gif', 'white fur', 'light gray body', 'purple stripes, orange mohawk', 'eyes, claws',
   ['A small white seal pup.', 'An orange mohawk of hair on the head.', 'Flippers with claws.']),
 d(126, 'meramon', '메라몬', 'Meramon', '성숙기', 'e/e2/Meramon_vpet_dm.gif', 'flame core', 'flame body', 'flame edges', 'eyes, mouth',
   ['A humanoid body made of fire.', 'Flames rising from the head and shoulders.']),
 d(131, 'rukamon', '돌핀몬', 'Rukamon', '완전체', 'e/eb/Rukamon_vpet_dv.gif', 'belly', 'light blue body', 'fins, dark stripes', 'eyes',
   ['A dolphin-like sea mammal.', 'Fins and a tail fin.']),
 d(135, 'lighdramon', '번개드라몬', 'Raidramon', '아머체', 'c/c0/Lighdramon_vpet_d3.gif', 'blade highlights', 'black armor', 'blue lightning blades', 'eyes',
   ['A four-legged armored dragon-dog.', 'Blades and horns along the back.', 'Lightning-shaped parts.']),
 d(140, 'andromon', '안드로몬', 'Andromon', '완전체', '3/30/Andromon_vpet_dm.gif', 'metal highlights', 'silver metal body', 'joints, chest machinery', 'eyes',
   ['A tall humanoid android.', 'A metal skull-like face.', 'Exposed machinery on the chest and arms.']),
 d(145, 'omegamon', '오메가몬', 'Omegamon', '궁극체', '8/85/Omegamon_vpet_dw.gif', 'armor highlights', 'white armor', 'cape, the wolf cannon arm', 'eyes',
   ['A white knight in armor with a long cape.', 'The LEFT arm is a dragon head (WarGreymon) with a sword.', 'The RIGHT arm is a wolf head (MetalGarurumon) cannon.']),
 d(168, 'diablomon', '디아블로몬', 'Diaboromon', '궁극체', '7/75/Diablomon_vpet_dt.gif', 'face mask', 'black body', 'red markings', 'eyes',
   ['A tall thin black demon with very long arms.', 'A white mask-like face.', 'Spiky shoulders and claws.']),
 d(173, 'plotmon', '플롯트몬', 'Salamon', '성장기', '9/9b/Plotmon_vpet_dw.gif', 'white fur', 'light fur', 'ear tips, collar', 'eyes',
   ['A small white puppy.', 'Long floppy ears.', 'A golden collar with a ring.']),
 d(175, 'patamon', '파닥몬', 'Patamon', '성장기', 'c/c9/Patamon_vpet_dv.gif', 'belly', 'orange body', 'bat-wing ears', 'eyes',
   ['A small round orange hamster-like body.', 'Big wing-like ears used to fly.', 'Four tiny legs.']),
 d(186, 'gekomon', '개굴몬', 'Gekomon', '성숙기', '3/3b/Gekomon_vpet_dv.gif', 'belly', 'green frog body', 'the three horns on the back', 'eyes',
   ['A green frog on two legs.', 'Horn-like trumpets on its back.', 'A wide mouth.']),
 d(195, 'imperialdramondragonmode', '황제드라몬', 'Imperialdramon (Dragon Mode)', '궁극체', '2/2a/Imperialdramon_vpet_d3.gif', 'armor highlights', 'black armor', 'red wings, cannon', 'eyes',
   ['A huge black dragon standing on ALL FOUR LEGS like a beast: the body is horizontal, chest low, both front legs on the ground.', 'Big red wings.', 'A long cannon mounted on the back.'],
   ['Do not draw it standing upright on two legs; it is NOT a humanoid. Fighter Mode (upright) is a different form.']),
]
