"""그림 주문서 v3 종별 값 (gen_order.py 가 읽음, ingest.py 가 pal·등급을 읽음)
 tier 1 = 지금 막힌 것 / 2 = 보스·암흑단·암흑 진화 / 3 = 갈래·유아기 / 0 = 후보(결정 대기)
 tones: 받을 그림의 회색 4톤이 각각 어느 부위인지. pal: 롬에 넣을 때 입힐 밝은·어두운 색 (흰색·검정은 고정)
 keep: 1번이 가장 중요. not: 그 종이 잘못 그려지는 방향을 미리 막음. keep_back: 뒤에서 보이는 것만
 wiki: 위키몬 문서 이름 (LCD 도트 찾기, lcd.json)"""

S = [
 # ── 1 지금 막힌 것 ──
 dict(id='metalgreymon', ko='메탈그레이몬', en='MetalGreymon', grade='완전체', tier=1, dir='metalgreymon-v', wiki='MetalGreymon', front_done=True,
      use='그레이몬 →(용기 문장) 메탈그레이몬 → 워그레이몬. 앞모습은 롬에 들어감 — 뒷모습만 다시',
      pal=((232, 128, 48), (96, 112, 136)),
      tones=dict(white='metal highlights', light='orange skin', dark='metal arm, helmet, chest plate, wings', black='outline, eyes, claws'),
      keep=['A huge silver metal LEFT arm with three long claws (the character\'s own left arm).',
            'A metal helmet covering the upper face, with one horn.',
            'A metal chest plate.',
            'Two torn purple bat-like wings on the back.',
            'Orange dinosaur body with blue stripes and a thick tail.'],
      not_=['Do not put the metal arm on the character\'s right arm.'],
      keep_back=['The big metal LEFT arm, on the LEFT side of the image in this rear view, with its three claws.',
                 'The two torn wings spread from the back.',
                 'The horned metal helmet seen from behind, one horn tip visible.',
                 'The thick tail at the bottom edge.'],
      not_back=['Do not put the metal arm on the right side of the image.']),
 dict(id='weregarurumon', ko='워가루몬', en='WereGarurumon', grade='완전체', tier=1, dir='weregarrumon', wiki='WereGarurumon',
      use='가루몬 →(우정 문장) 워가루몬 → 메탈가루몬. 지금은 물음표 알',
      pal=((136, 184, 240), (40, 72, 160)),
      tones=dict(white='white fur, bandages on the fists', light='blue fur patches, the mane, the jeans', dark='belts, shoulder strap, spiked shoulder pad', black='claws'),
      keep=['A muscular werewolf standing upright on two legs.',
            'A big spiky mane around the head and shoulders.',
            'Ripped jeans; one strap crossing the chest with a spiked shoulder pad on one shoulder.',
            'Bandaged fists with big claws.'],
      not_=['Not a four-legged wolf.', 'No skull emblem, no small stitches, no fur stripes smaller than a few pixels.'],
      keep_back=['The spiky mane from behind.', 'The strap crossing the back.', 'The spiked pad on the right shoulder.', 'The tail.']),
 dict(id='tunomon', ko='뿔몬', en='Tsunomon', grade='유년기Ⅱ', tier=1, dir='tunomon', wiki='Tunomon',
      use='29~32번 도로 야생 (러브리몬 칸) → Lv11 파피몬',
      pal=((232, 168, 96), (128, 72, 40)),
      tones=dict(white='the face', light='orange-brown fur', dark='the horn, fur shading', black='eyes'),
      keep=['ONE long curved horn growing from the top of the head.',
            'A round ball body with NO arms and NO legs.',
            'Shaggy fur around the face, the face is pale.',
            'Big round eyes, small open mouth.'],
      not_=['No arms, no legs, no feet.', 'Only one horn, not two.'],
      keep_back=['The round furry back.', 'The horn sticking up above the head.']),
 dict(id='tokomon', ko='토코몬', en='Tokomon', grade='유년기Ⅱ', tier=1, dir='tokomon', wiki='Tokomon',
      use='29~31번 도로 밤 야생 (팔코몬 칸) + 공박사 조수의 알 → Lv10 파닥몬',
      pal=((248, 184, 192), (200, 64, 72)),
      tones=dict(white='the round body', light='inside of the ears, cheeks', dark='inside of the mouth, eyes', black='outline'),
      keep=['A tiny round white body like a marshmallow.',
            'Two long thin ear-feelers on top of the head.',
            'Two very short stubby feet and two tiny arms.',
            'Small red eyes, a small mouth.'],
      not_=['No tail, no wings.', 'Not a rabbit or a hamster.'],
      keep_back=['The round white back.', 'The two ear-feelers.', 'The stubby feet at the bottom.']),
 dict(id='pyocomon', ko='어니몬', en='Yokomon', grade='유년기Ⅱ', tier=1, dir='pyocomon', wiki='Pyocomon',
      use='32·33번 도로 야생 (통통코 칸) → Lv12 피요몬',
      pal=((248, 184, 200), (64, 104, 200)),
      tones=dict(white='highlight on the body', light='pale pink bulb body', dark='the big flower on the head', black='eyes'),
      keep=['A large flower with wide petals on top of the head, almost as wide as the body.',
            'An onion-bulb body with NO arms and NO legs, a few tiny root stubs at the bottom.',
            'A curly stamen rising from the center of the flower.',
            'Small eyes and a tiny mouth.'],
      not_=['No arms, no legs.', 'Not a potted plant.'],
      keep_back=['The flower seen from behind on top.', 'The round bulb back.', 'The root stubs at the bottom.']),
 dict(id='mochimon', ko='모티몬', en='Motimon', grade='유년기Ⅱ', tier=1, dir='mochimon', wiki='Mochimon',
      use='32번 도로 야생 (메리프 칸) → Lv12 텐타몬',
      pal=((248, 192, 208), (176, 88, 120)),
      tones=dict(white='highlights', light='soft pink body', dark='inside of the mouth, the tiny claws', black='eyes'),
      keep=['A soft pink rice-cake body shaped like a little ghost, the bottom edge is wavy, NO legs.',
            'Two stubby arms, each with tiny dark claws.',
            'Big round black eyes.',
            'An open happy mouth.'],
      not_=['No legs, no tail.', 'Not a flat slime puddle.'],
      keep_back=['The rounded back.', 'The wavy bottom edge.', 'The stubby arms at the sides.']),
 dict(id='tanemon', ko='시드몬', en='Tanemon', grade='유년기Ⅱ', tier=1, dir='tanemon', wiki='Tanemon',
      use='너도밤나무 숲 야생 (파라스 칸) → Lv11 팔몬',
      pal=((168, 216, 104), (48, 120, 56)),
      tones=dict(white='the cream face', light='green top of the bulb', dark='the leaves, the little feet', black='eyes'),
      keep=['An onion-bulb body: green on top, cream face below.',
            'Two long leaves sprouting from the top of the head.',
            'Four tiny root-like feet under the body.',
            'Big eyes, a small cat-like mouth.'],
      not_=['No arms.', 'Not a frog.'],
      keep_back=['The green bulb back.', 'The leaves on top.', 'The little feet at the bottom.']),
 dict(id='pukamon', ko='둥실몬', en='Bukamon', grade='유년기Ⅱ', tier=1, dir='pukamon', wiki='Pukamon',
      use='낚시 (콘치 칸) → Lv13 쉬라몬',
      pal=((184, 192, 208), (232, 96, 40)),
      tones=dict(white='belly, inside of the mouth', light='gray body, flippers', dark='the flame tuft on the head, tail fin shading', black='eyes'),
      keep=['A big HEAVY LOWER JAW: the mouth is the widest part of the head and sticks out forward.',
            'NO LEGS. A plump seal-like baby with two front flippers and a fish tail.',
            'A flame-shaped tuft of hair on top of the head.',
            'A round body, almost as wide as tall.'],
      not_=['No legs, no feet, no arms with fingers.', 'No wings.'],
      keep_back=['The round back.', 'The flame tuft on top.', 'The tail fin at the bottom edge.', 'The flippers at the sides.']),
 dict(id='gazimon', ko='가지몬', en='Gazimon', grade='성장기', tier=1, dir='gazimon', wiki='Gazimon',
      use='어둠의 동굴 야생 (노고치 칸)',
      pal=((184, 180, 200), (88, 80, 120)),
      tones=dict(white='muzzle and belly', light='gray fur', dark='stripes on the ears and back', black='claws, eyes'),
      keep=['Very long rabbit-like ears with dark stripes.',
            'Stands on two legs in a hunched, sly pose.',
            'Long sharp claws on both hands.',
            'A sly grin with sharp teeth, red eyes.'],
      not_=['Not a cute bunny.', 'No clothes, no wings.'],
      keep_back=['The long striped ears.', 'The striped back.', 'The claws at the sides.']),
 dict(id='bakemon', ko='고스몬', en='Bakemon', grade='성숙기', tier=1, dir='bakemon', wiki='Bakemon',
      use='모다피의 탑·암흑단 조직원 (임프몬 칸)',
      pal=((200, 200, 216), (56, 48, 80)),
      tones=dict(white='the sheet (most of the body)', light='folds and shading on the sheet', dark='the dark hole where the face is', black='eyes, teeth'),
      keep=['A floating ghost wearing a plain white sheet; the sheet is the whole body.',
            'A large dark opening in the sheet where the face would be, with two glowing eyes and a row of sharp teeth inside it.',
            'Two clawed hands coming out of the sheet at the sides.',
            'The bottom of the sheet is a wavy tail, no legs.'],
      not_=['No legs, no feet.', 'No hat, no horns, no wings.', 'Not a solid-body creature; it must read as a cloth sheet.'],
      keep_back=['The sheet seen from behind with its wavy bottom.', 'One claw peeking at the side.', 'No face.']),
 dict(id='kuwagamon', ko='쿠가몬', en='Kuwagamon', grade='성숙기', tier=1, dir='kuwagamon', wiki='Kuwagamon',
      use='36번 도로 길막 보스 (꼬지모 칸 185) · 텐타몬 유대 낮음 갈래',
      pal=((224, 64, 48), (88, 88, 104)),
      tones=dict(white='belly plates, inner edges of the pincers', light='red shell (head, back, limbs)', dark='wing membranes, joints, deep shadow under the shell', black='eyes, mouth'),
      keep=['Two HUGE stag-beetle pincers growing from the head, each longer than the head itself, with jagged inner edges.',
            'A long red beetle body standing upright on two legs, with FOUR thin arms on the torso.',
            'Four insect wings on the back.',
            'A toothy mouth between the pincers.'],
      not_=['Do not shrink the pincers into small horns.', 'Do not give it a round bulky bug body or stubby arms.', 'Do not add features from other monsters.'],
      keep_back=['Wings covering the back.', 'Pincer tips visible above the head.', 'Thin arms at the sides.']),
 dict(id='shellmon', ko='쉘몬', en='Shellmon', grade='성숙기', tier=1, dir='shellmon', wiki='Shellmon',
      use='낚시꾼·바닷가 트레이너, 사천왕 일목 (셀러 칸)',
      pal=((240, 144, 168), (80, 104, 136)),
      tones=dict(white='shell highlights, teeth', light='pink skin', dark='the gray-blue shell, the green hair', black='eyes'),
      keep=['A big spiked conch shell carried on its back behind the head, like a hermit crab. The shell does NOT cover the whole body.',
            'A pink, low, dinosaur-like body crawling on four short legs.',
            'Seaweed-like hair sticking out on top of the head.',
            'An open mouth with small teeth.'],
      not_=['Not a snail hiding inside its shell.', 'Not a turtle.', 'No tentacles.'],
      keep_back=['The big spiked shell from behind.', 'The hair tufts.', 'The short legs at the sides.']),
 dict(id='monochromon', ko='모노크로몬', en='Monochromon', grade='성숙기', tier=1, dir='monochromon', wiki='Monochromon',
      use='등산가 트레이너, 사천왕 시바 (롱스톤 칸)',
      pal=((176, 176, 184), (72, 72, 88)),
      tones=dict(white='horn and beak highlights', light='gray body', dark='the dark armor plates on the head frill and back', black='eyes'),
      keep=['ONE long horn on the nose.',
            'A big triceratops-like frill behind the head.',
            'A heavy four-legged dinosaur body with armor plates on the back.',
            'Small eyes and a beak-like mouth.'],
      not_=['Not two or three horns.', 'Not standing upright.'],
      keep_back=['The frill and back plates from behind.', 'The horn tip visible past the head.', 'The thick legs.']),
 dict(id='numemon', ko='워매몬', en='Numemon', grade='성숙기', tier=1, dir='numemon', wiki='Numemon',
      use='초반 트레이너, 사천왕 독수 (질퍽이 칸)',
      pal=((176, 208, 96), (136, 64, 152)),
      tones=dict(white='teeth, eye whites', light='green slug body', dark='the tongue, the spots', black='pupils'),
      keep=['Two eyes on long stalks, bloodshot.',
            'A huge mouth with big teeth and the tongue sticking out.',
            'A slug body with NO arms and NO legs.',
            'Spots on the body.'],
      not_=['No arms, no legs.', 'No snail shell.'],
      keep_back=['The slimy hump.', 'The two eye stalks above it.']),
 dict(id='seadramon', ko='시드라몬', en='Seadramon', grade='성숙기', tier=1, dir='seadramon', wiki='Seadramon',
      use='베타몬 → 시드라몬 → 메가시라몬 줄, 쉬라몬 유대 낮음 갈래 (왕콘치 칸)',
      pal=((240, 216, 96), (48, 144, 160)),
      tones=dict(white='teeth, eye shine', light='the yellow mask and belly', dark='the teal body, the tail fin', black='eyes'),
      keep=['A long sea-serpent body coiled in an S shape, NO arms and NO legs.',
            'A yellow helmet-like mask covering the top of the head, with a crest.',
            'Long jaws.',
            'A fin at the tip of the tail.'],
      not_=['No legs, no arms, no wings.', 'Not a whiskered Chinese dragon.'],
      keep_back=['The coiled body.', 'The back of the mask.', 'The tail fin.']),
 dict(id='centalmon', ko='켄터스몬', en='Centarumon', grade='성숙기', tier=1, dir='centalmon', wiki='Centalmon',
      use='초반 트레이너, 사천왕 시바 (켄타로스 칸)',
      pal=((216, 176, 120), (64, 96, 176)),
      tones=dict(white='armor highlights', light='the tan horse body and skin', dark='the blue armor plates and helmet', black='the eye'),
      keep=['A centaur: a humanoid upper body on a four-legged horse body.',
            'A helmet with ONE eye.',
            'An arm cannon on one arm.',
            'Blue armor plates on the shoulders and chest.'],
      not_=['No wings.', 'Not a plain horse.'],
      keep_back=['The armored back.', 'The four legs.', 'The arm cannon at one side.']),
 # ── 2 보스·암흑단·암흑 진화 ──
 dict(id='vamdemon', ko='묘티스몬', en='Myotismon', grade='완전체', tier=2, dir='vamdemon', wiki='Vamdemon',
      use='암흑단 우두머리 (라디오 타워 꼭대기), 크로뱃 칸',
      pal=((216, 64, 64), (48, 48, 104)),
      tones=dict(white='pale face and hair', light='red bat mask, red cape lining', dark='dark suit, outside of the cape', black='eyes'),
      keep=['A tall vampire lord with a huge cape spreading out behind him.',
            'A red bat-shaped mask over the eyes.',
            'A dark suit with a high collar.',
            'Long thin arms with claws.'],
      not_=['Not a bat monster.', 'No wings (only the cape).', 'No horns.'],
      keep_back=['The cape covering the back.', 'The high collar.', 'The hair.']),
 dict(id='fantomon', ko='팬텀몬', en='Phantomon', grade='완전체', tier=2, dir='fantomon', wiki='Fantomon',
      use='암흑단 간부 (아지트)',
      pal=((200, 184, 232), (64, 48, 96)),
      tones=dict(white='the skull face, bony hands', light='light parts of the cloak', dark='the dark hooded cloak', black='eye holes'),
      keep=['A floating grim reaper in a ragged hooded cloak, no legs.',
            'A big scythe.',
            'A skull-like face inside the hood.',
            'Bony hands.'],
      not_=['No legs, no wings.', 'Not a knight in armor.'],
      keep_back=['The hood and ragged cloak from behind.', 'The scythe blade above the shoulder.']),
 dict(id='devidramon', ko='데블드라몬', en='Devidramon', grade='성숙기', tier=2, dir='devidramon', wiki='Devidramon',
      use='암흑단 간부 (아지트)',
      pal=((200, 64, 64), (56, 40, 64)),
      tones=dict(white='claw tips, teeth', light='red eyes and wing membranes', dark='the dark body', black='outline'),
      keep=['FOUR glowing eyes.',
            'Huge bat-like wings.',
            'Very long arms with big claws.',
            'A dark dragon body.'],
      not_=['Not a two-eyed dragon.', 'Not a Western dragon breathing fire.'],
      keep_back=['The wings spread from the back.', 'The long arms at the sides.']),
 dict(id='skullgreymon', ko='스컬그레이몬', en='SkullGreymon', grade='완전체', tier=2, dir='skullgreymon', wiki='SkullGreymon',
      use='그레이몬 암흑 진화 (유대 낮음 + 자기 문장 없음)',
      pal=((232, 224, 200), (120, 112, 96)),
      tones=dict(white='bone highlights', light='bones', dark='the missile, shadows inside the ribcage', black='eye holes'),
      keep=['A dinosaur skeleton made of bare bones: skull head, ribcage, bony limbs.',
            'A big missile mounted along its back.',
            'A hunched, aggressive pose with a long bony tail.',
            'Glowing eyes in the skull.'],
      not_=['No flesh or skin.', 'Not a living dinosaur.'],
      keep_back=['The spine and the missile on it.', 'The bony tail.']),
 dict(id='ladydevimon', ko='레이디데블몬', en='LadyDevimon', grade='완전체', tier=2, dir='ladydevimon', wiki='LadyDevimon',
      use='가트몬 암흑 진화, 사천왕 카렌',
      pal=((200, 200, 216), (64, 40, 72)),
      tones=dict(white='pale skin', light='silver hair', dark='the black outfit and wings', black='outline'),
      keep=['A slim female demon in a tight black outfit.',
            'Huge tattered bat wings.',
            'A mask over the eyes and long silver hair.',
            'Long claws.'],
      not_=['Not an angel.', 'No horns on the head.'],
      keep_back=['The tattered wings.', 'The long hair from behind.']),
 dict(id='angewomon', ko='엔젤우몬', en='Angewomon', grade='완전체', tier=2, dir='angewomon', wiki='Angewomon',
      use='가트몬 →(빛 문장) 엔젤우몬, 레드(태일) 파티',
      pal=((248, 216, 112), (208, 104, 152)),
      tones=dict(white='wings and bodysuit', light='blond hair', dark='the ribbon sash and helmet', black='outline'),
      keep=['A female angel with EIGHT white wings.',
            'A helmet that covers her eyes.',
            'Long blond hair.',
            'A long ribbon sash floating around her.'],
      not_=['No halo, no sword.', 'Not a child.'],
      keep_back=['Eight wings from behind.', 'Long hair.', 'The ribbon sash.']),
 dict(id='monzaemon', ko='퍼펫몬', en='Monzaemon', grade='완전체', tier=2, dir='monzaemon', wiki='Monzaemon',
      use='관동 길막 (잠만보 칸) — 잠든 거대한 인형, 라디오로 깨움',
      pal=((248, 208, 72), (176, 120, 40)),
      tones=dict(white='the round belly', light='yellow fur', dark='paws, ears, shading', black='eyes'),
      keep=['A giant teddy bear.',
            'A big white round belly.',
            'Small round ears and small black eyes.',
            'Short thick arms and legs.'],
      not_=['Not a real bear; it is a stuffed toy.', 'No clothes.'],
      keep_back=['The round back.', 'The small ears.']),
 dict(id='metalseadramon', ko='메탈시드라몬', en='MetalSeadramon', grade='궁극체', tier=2, dir='metalseadramon', wiki='MetalSeadramon',
      use='사천왕 일목의 에이스 (어둠의 4천왕)',
      pal=((232, 208, 96), (112, 128, 160)),
      tones=dict(white='metal highlights', light='gold armor plates', dark='silver armor, the mane', black='eyes'),
      keep=['A long sea serpent covered in shiny metal armor, coiled in an S shape.',
            'A pointed metal head with a cannon on the nose.',
            'A wild mane behind the head.',
            'NO arms and NO legs.'],
      not_=['No legs, no arms.', 'Not a fish.'],
      keep_back=['The armored coils.', 'The mane.']),
 dict(id='mugendramon', ko='파워드라몬', en='Machinedramon', grade='궁극체', tier=2, dir='mugendramon', wiki='Mugendramon',
      use='사천왕 시바의 에이스 (어둠의 4천왕)',
      pal=((176, 176, 192), (72, 72, 88)),
      tones=dict(white='metal highlights', light='light metal parts', dark='dark metal body', black='eyes'),
      keep=['TWO huge round cannons mounted on its back over the shoulders.',
            'A gigantic dinosaur made entirely of metal.',
            'A mechanical jaw with red eyes.',
            'Big metal claws on hands and feet.'],
      not_=['No wings.', 'Not a robot humanoid.'],
      keep_back=['The two cannons on the back.', 'The tail.']),
 dict(id='pinochimon', ko='피노키몬', en='Puppetmon', grade='궁극체', tier=2, dir='pinochimon', wiki='Pinochimon',
      use='사천왕 독수의 에이스 (어둠의 4천왕)',
      pal=((232, 168, 104), (200, 56, 56)),
      tones=dict(white='gloves', light='wooden face and body', dark='the pointed hat, clothes', black='eyes'),
      keep=['A wooden puppet boy with a long wooden nose.',
            'A giant wooden hammer.',
            'A pointed hat.',
            'A wooden cross on his back with puppet strings.'],
      not_=['Not a real child.', 'No wings.'],
      keep_back=['The wooden cross and strings on the back.', 'The hammer over the shoulder.']),
 dict(id='apocalymon', ko='아포카리몬', en='Apocalymon', grade='궁극체', tier=2, dir='apoclymon', wiki='Apocalymon',
      use='챔피언(목호)의 에이스, 마지막 적',
      pal=((232, 200, 80), (48, 56, 112)),
      tones=dict(white='highlights', light='gold edges', dark='the dark many-sided body', black='outline'),
      keep=['A many-sided crystal-like body with gold edges, a point at the bottom.',
            'A small dark head on top.',
            'Long chains coming out of it, ending in spiked balls and claws.',
            'NO arms and NO legs.'],
      not_=['No legs.', 'Not a humanoid.'],
      keep_back=['The many-sided body from behind.', 'Chains at the sides.']),
 # ── 3 갈래·유아기 ──
 dict(id='tyranomon', ko='티라노몬', en='Tyrannomon', grade='성숙기', tier=3, dir='tyranomon', wiki='Tyranomon',
      use='아구몬 유대 낮음 갈래 (파라섹트 칸)',
      pal=((232, 96, 72), (64, 144, 72)),
      tones=dict(white='belly', light='red body', dark='green back spikes', black='eyes, claws'),
      keep=['A red tyrannosaurus standing on two strong legs.', 'A white belly.', 'Spikes along its back.', 'Short arms with big claws.'],
      not_=['No armor, no helmet.', 'Not orange like Greymon; no horns.'],
      keep_back=['The back spikes.', 'The thick tail.']),
 dict(id='vegimon', ko='베지몬', en='Vegiemon', grade='성숙기', tier=3, dir='vegimon', wiki='Vegimon',
      use='팔몬 유대 낮음 갈래 (덩구리 칸)',
      pal=((168, 208, 88), (120, 64, 152)),
      tones=dict(white='teeth', light='green body', dark='petals on top, vine shading', black='eyes'),
      keep=['A round green plant body.', 'A big mouth like a flytrap with sharp teeth.', 'A crown of petals on top.', 'Long vine arms.'],
      not_=['No legs with feet.', 'Not a cute flower.'],
      keep_back=['The petal crown.', 'The vine arms.']),
 dict(id='kiwimon', ko='키위몬', en='Kiwimon', grade='성숙기', tier=3, dir='kiwimon', wiki='Kiwimon',
      use='피요몬 유대 낮음 갈래 (두두 칸)',
      pal=((136, 200, 96), (152, 104, 64)),
      tones=dict(white='the white body', light='green feather crest', dark='brown lower body, legs', black='eyes'),
      keep=['A kiwi bird with a long beak.', 'A spiky crest of feathers on the head.', 'Long legs with claws.', 'NO wings.'],
      not_=['No wings.', 'Not a chicken.'],
      keep_back=['The feather crest.', 'The round back.']),
 dict(id='botamon', ko='깜몬', en='Botamon', grade='유아기Ⅰ', tier=3, dir='botamon', wiki='Botamon',
      use='알 전용 → 코로몬',
      pal=((240, 216, 72), (64, 64, 72)),
      tones=dict(white='eye shine', light='the yellow eyes', dark='the black fuzzy body', black='outline'),
      keep=['ONE round fuzzy ball covered in short spiky fur.', 'Two small ear bumps on top.', 'Two glowing yellow eyes.', 'No mouth, no arms, no legs.'],
      not_=['No arms, no legs, no tail.'],
      keep_back=['The fuzzy round back.', 'The ear bumps.']),
 dict(id='punimon', ko='푸니몬', en='Punimon', grade='유아기Ⅰ', tier=3, dir='punimon', wiki='Punimon',
      use='알 전용 → 뿔몬',
      pal=((232, 80, 80), (152, 32, 48)),
      tones=dict(white='big eyes', light='red jelly body', dark='shading', black='pupils'),
      keep=['A shiny red jelly dome.', 'Short rounded horn bumps on top.', 'Two big round eyes.', 'No arms, no legs.'],
      not_=['No arms, no legs, no spikes.'],
      keep_back=['The jelly dome back.', 'The horn bumps.']),
 dict(id='nyaromon', ko='야옹몬', en='Nyaromon', grade='유년기Ⅱ', tier=3, dir='nyaromon', wiki='Nyaromon',
      use='알 전용 → 플롯트몬',
      pal=((248, 224, 104), (152, 96, 176)),
      tones=dict(white='eye shine', light='yellow head', dark='tail stripes and tip, inside of the ears', black='eyes'),
      keep=['A round cat head with NO body.', 'Two big pointed cat ears.', 'One long striped tail coming out of the back of the head.', 'No arms, no legs.'],
      not_=['No body, no legs.'],
      keep_back=['The back of the head with the ears.', 'The striped tail.']),
 # ── 0 후보 (계획 결정 뒤 주문) ──
 dict(id='qinglongmon', ko='청룡몬', en='Azulongmon', grade='궁극체', tier=0, dir='qinglongmon', wiki='Qinglongmon',
      use='후보: 방울탑 전설 (칠색조 칸) — 02 34화에 나옴',
      pal=((136, 184, 240), (40, 72, 160)),
      tones=dict(white='glowing orbs, highlights', light='light blue scales', dark='dark blue scales, horns', black='eyes'),
      keep=['A long serpentine eastern dragon body coiling.', 'Antler-like horns.', 'Glowing orbs around its body.', 'Small clawed limbs.'],
      not_=['No wings.', 'Not a Western dragon.'],
      keep_back=['The coils from behind.', 'The horns.']),
 dict(id='whamon', ko='고래몬', en='Whamon', grade='완전체', tier=0, dir='whamon', wiki='Whamon',
      use='후보: 소용돌이 섬 전설 (루기아 칸) — 어드벤처 14화',
      pal=((120, 168, 232), (40, 72, 152)),
      tones=dict(white='belly', light='light blue body', dark='dark blue back', black='eyes'),
      keep=['A huge whale.', 'A wide mouth.', 'A white underside.', 'Small eyes.'],
      not_=['No legs.', 'Not a fish with scales.'],
      keep_back=['The broad back.', 'The tail.']),
 # ── 4 로스터 ★ 중 카드 없던 종 (S11 후속 2026-10-06; 그림은 wikimon 공식 그림을 보고 적음. tier: 3 일반·2 보스/암흑단/사천왕·0 2부) ──
 dict(id='nyokimon', ko='뇨키몬', en='Nyokimon', grade='유아기Ⅰ', tier=3, dir='nyokimon', wiki='Nyokimon',
      use='알 전용 → 어니몬 (파트너 줄, 칸 241)',
      pal=((176, 208, 72), (56, 48, 48)),
      tones=dict(white='body shine', light='the green leaves', dark='the black fuzzy body', black='outline, eyes'),
      keep=['A black fuzzy round seed-shaped body.', 'Two green leaves sprouting from the top.', 'Two glowing yellow eyes and a tiny pink mouth.', 'No arms, no legs.'],
      not_=['No arms, no legs, no tail.', 'Not a flower; only two seed leaves.'],
      keep_back=['The two leaves on top.', 'The fuzzy round back.']),
 dict(id='bubbmon', ko='파브몬', en='Bubbmon', grade='유아기Ⅰ', tier=3, dir='bubbmon', wiki='Bubbmon',
      use='알 전용 → 모티몬 (파트너 줄, 칸 233)',
      pal=((184, 216, 128), (88, 120, 72)),
      tones=dict(white='bubble shine', light='the pale green slime', dark='the darker green edge', black='eyes'),
      keep=['A flat blob of green slime with a wavy skirt-like bottom edge.', 'Two small black round eyes.', 'Several clear bubbles on top and at the side.', 'No arms, no legs.'],
      not_=['No limbs, no mouth line.', 'Not a water drop; it is a slime blob.'],
      keep_back=['The smooth slime back.', 'The bubbles on top.']),
 dict(id='yuramon', ko='유라몬', en='Yuramon', grade='유아기Ⅰ', tier=3, dir='yuramon', wiki='Yuramon',
      use='알 전용 → 시드몬 (파트너 줄, 칸 234)',
      pal=((232, 224, 176), (104, 88, 160)),
      tones=dict(white='cream fur', light='cream tufts', dark='purple eye patch and purple tendril tips', black='eyes, outline'),
      keep=['A floating round ball of cream-colored fluffy tufts.', 'A purple patch around two round black eyes.', 'Two long curly purple tendrils on top.', 'No arms, no legs.'],
      not_=['No arms, no legs, no mouth.', 'Not a plain fur ball; the tufts overlap like petals.'],
      keep_back=['The tuft-covered round back.', 'The two curled tendrils.']),
 dict(id='pitchmon', ko='피치몬', en='Pitchmon', grade='유아기Ⅰ', tier=3, dir='pitchmon', wiki='Pitchmon',
      use='알 전용 → 둥실몬 (파트너 줄, 칸 235)',
      pal=((168, 208, 240), (56, 104, 168)),
      tones=dict(white='shine', light='pale blue skin', dark='blue shading', black='outline, the pointed tip'),
      keep=['A small pale-blue body shaped like a water drop.', 'Two long pointed ears standing up.', 'One big round red eye with a white shine.', 'Small bumps along the back and a small black pointed tip at the bottom.'],
      not_=['No arms, no legs.', 'Not a rabbit; the ears are thin and smooth, no fluffy tail.'],
      keep_back=['The two long ears.', 'The bumps along the back.']),
 dict(id='poyomon', ko='포요몬', en='Poyomon', grade='유아기Ⅰ', tier=3, dir='poyomon', wiki='Poyomon',
      use='알 전용 → 토코몬 (파트너 줄, 칸 237)',
      pal=((184, 216, 248), (72, 128, 200)),
      tones=dict(white='shine', light='pale blue-white jelly', dark='light blue at the bottom edge', black='eyes, outline'),
      keep=['A soft ghost-shaped jelly body with a wavy bottom edge.', 'Two black round eyes.', 'A small orange smile.', 'No arms, no legs.'],
      not_=['No arms, no legs, no ears.', 'Not a sheet ghost; a soft rounded jelly.'],
      keep_back=['The rounded jelly back.', 'The wavy bottom edge.']),
 dict(id='yukimibotamon', ko='유키보타몬', en='Yukimi Botamon', grade='유아기Ⅰ', tier=3, dir='yukimibotamon', wiki='Yukimibotamon',
      use='알 전용 → 야옹몬 (파트너 줄, 칸 222)',
      pal=((248, 248, 255), (160, 176, 216)),
      tones=dict(white='most of the body', light='pale blue shading', dark='gray-blue shading', black='eyes, outline'),
      keep=['A round white fluffy ball with two round ears.', 'Two big black eyes with a white shine.', 'A tiny cat-like mouth and pink cheeks.', 'No arms, no legs.'],
      not_=['No arms, no legs.', 'Not black like Botamon; this one is white.'],
      keep_back=['The two round ears.', 'The round white back.']),
 dict(id='unimon', ko='유니몬', en='Unimon', grade='성숙기', tier=3, dir='unimon', wiki='Unimon',
      use='야생(절구산·37번 도로)·고정(모다피의 탑 꼭대기 Lv12) (칸 77)',
      pal=((216, 216, 224), (48, 48, 64)),
      tones=dict(white='white body', light='gray fur', dark='black wings', black='hooves, outline'),
      keep=['A white winged horse standing on four legs.', 'Large black feathered wings spread upward.', 'A red visor-like mask over the eyes with a horn on the forehead.', 'A yellow mane and steel-gray hooves.'],
      not_=['The wings are black, not white.', 'No rider, no saddle.'],
      keep_back=['The black wings seen from behind.', 'The long tail and mane.']),
 dict(id='mojyamon', ko='모야몬', en='Mojyamon', grade='성숙기', tier=3, dir='mojyamon', wiki='Mojyamon',
      use='야생(얼음샛길) (칸 221) — needs.json 은 모야몬 dir 가 nanimon 으로 되어 있어(나니몬과 겹침) 이 카드는 mojyamon 으로 둠',
      pal=((232, 240, 248), (104, 96, 144)),
      tones=dict(white='white shaggy fur', light='pale blue-gray fur', dark='purple shadow in the fur', black='eyes, mouth'),
      keep=['A big shaggy white yeti with wild fur.', 'Huge hands with big human-like fingers.', 'A fierce open mouth with fangs and angry eyes.', 'A purple star-shaped mark on top of the head and big bare feet.'],
      not_=['Not a cute monkey.', 'No clothes, no weapons.'],
      keep_back=['The shaggy white back.', 'The huge hands.']),
 dict(id='yukidarumon', ko='프리지몬', en='Yukidarumon', grade='성숙기', tier=3, dir='yukidarumon', wiki='Yukidarumon',
      use='야생(얼음샛길·45번 도로) (칸 220)',
      pal=((232, 244, 255), (80, 152, 216)),
      tones=dict(white='snow body', light='pale blue shading', dark='blue ice swirl', black='eyes, nose'),
      keep=['A white snowman-like bear with a round head and two round ears.', 'Small black dot eyes and nose.', 'Two red buttons on the chest.', 'One huge arm; a swirl of icy wind around the feet.'],
      not_=['No scarf, no carrot nose, no top hat.', 'Not a polar bear.'],
      keep_back=['The big round back.', 'The huge arm.']),
 dict(id='tonosamagekomon', ko='왕개굴몬', en='Tonosama Gekomon', grade='완전체', tier=3, dir='tonosamagekomon', wiki='Tonosamagekomon',
      use='고정(연분홍 등대 또는 야돈 우물 안쪽 Lv28, 포획 30) (칸 199)',
      pal=((224, 64, 56), (224, 208, 72)),
      tones=dict(white='horn shine', light='red body, yellow belly', dark='green leaf collar, shadow', black='eyes, outline'),
      keep=['A big red frog with a huge round yellow belly.', 'Two large golden trumpet-like horns on its head.', 'A collar of green leaves around the neck.', 'A purple hair tuft on top and long thin red arms.'],
      not_=['Not a plain green frog.', 'No clothes other than the leaf collar.'],
      keep_back=['The golden horns.', 'The round yellow belly outline.']),
 dict(id='drimogemon', ko='드리모게몬', en='Drimogemon', grade='성숙기', tier=3, dir='drimogemon', wiki='Drimogemon',
      use='야생(돌산 터널·연결동굴) (칸 50)',
      pal=((248, 240, 176), (56, 72, 152)),
      tones=dict(white='steel shine of the drills', light='cream fur', dark='blue hair on the head and back', black='eyes, mouth, drill shadow'),
      keep=['A cream-colored mole-like beast standing on thick legs.', 'A big steel drill in place of the nose.', 'Blue hair along the head and back.', 'Small steel drills on the claws and a wide mouth with sharp teeth.'],
      not_=['No wings, no armor.', 'Not a dog or a bear.'],
      keep_back=['The blue hair along the back.', 'The drill pointing forward over the head.']),
 dict(id='scumon', ko='슈카몬', en='Scumon', grade='성숙기', tier=3, dir='scumon', wiki='Scumon',
      use='야생(쓰레기·야돈 우물) (칸 89)',
      pal=((248, 216, 48), (232, 56, 56)),
      tones=dict(white='shine on the body', light='yellow body', dark='yellow shading, gray metal rings', black='eyes, outline, claws'),
      keep=['A yellow swirl-shaped body with a pointed top.', 'A huge grin full of teeth and a long red tongue.', 'Large round eyes.', 'Two long thin mechanical arms with black rings and sharp claws.'],
      not_=['No legs.', 'Not a cute face; the grin is wide and creepy.'],
      keep_back=['The swirl-shaped yellow back.', 'The two long arms.']),
 dict(id='tyumon', ko='츄몬', en='Tyumon', grade='성장기', tier=3, dir='tyumon', wiki='Tyumon',
      use='야생(쓰레기·야돈 우물) (칸 162)',
      pal=((248, 128, 184), (168, 48, 120)),
      tones=dict(white='teeth, eye whites', light='pink body', dark='darker pink shading', black='outline, claws'),
      keep=['A bright pink mouse standing upright with a lean body.', 'Two big round ears with small spikes.', 'Big buck teeth and one big eye looking sideways.', 'Long thin arms with sharp black claws.'],
      not_=['Not a cute mouse.', 'No clothes.'],
      keep_back=['The back of the head with the two ears.', 'The thin pink body.']),
 dict(id='cockatrimon', ko='꼬끼몬', en='Cockatrimon', grade='성숙기', tier=3, dir='cockatrimon', wiki='Cockatrimon',
      use='야생(34번 도로·배)·고정(배 안 Lv22) (칸 83)',
      pal=((240, 232, 208), (216, 64, 40)),
      tones=dict(white='white feathers', light='cream feathers', dark='gray and purple feather shading', black='beak, claws, eyes'),
      keep=['A large rooster-like bird standing on two strong clawed legs.', 'White and cream feathers spreading outward like a fan.', 'Orange-red flame-shaped tips on the feathers.', 'A yellow beak with a red open mouth.'],
      not_=['No arms; wings only.', 'Not a phoenix; no golden glow.'],
      keep_back=['The fan of feathers from behind.', 'The red feather tips.']),
 dict(id='nanomon', ko='데이터몬', en='Nanomon', grade='완전체', tier=2, dir='nanomon', wiki='Nanomon',
      use='보스(피라미드 안 Lv30, 에테몬 직전) (칸 137)',
      pal=((192, 200, 208), (72, 72, 80)),
      tones=dict(white='glass dome shine', light='light gray metal', dark='dark gray metal', black='gaps, outline'),
      keep=['A small machine body inside a clear glass dome on a thin body.', 'Two long thin mechanical arms ending in many-fingered hands.', 'Dark gray joints and thin legs with pointed feet.', 'Tiny gauges and wires visible inside the dome.'],
      not_=['Not a humanoid knight.', 'No weapon other than the hands.'],
      keep_back=['The glass dome from behind.', 'The long arms.']),
 dict(id='nanimon', ko='나니몬', en='Nanimon', grade='성숙기', tier=3, dir='nanimon', wiki='Nanimon',
      use='야생(34번 도로) (칸 106)',
      pal=((208, 48, 40), (40, 32, 32)),
      tones=dict(white='sunglasses shine', light='red gloves and skin', dark='shadow, blue shorts', black='spiky hair, sunglasses band, outline'),
      keep=['A muscular boxer-like man with huge red gloves.', 'Spiky black hair and dark sunglasses.', 'Blue shorts with a yellow star mark.', 'A leaping punching pose.'],
      not_=['Not a cute character.', 'No shirt.'],
      keep_back=['The spiky black hair.', 'The broad muscular back.']),
 dict(id='vademon', ko='베이더몬', en='Vademon', grade='완전체', tier=3, dir='vademon', wiki='Vademon',
      use='고정(알프의 유적 방 Lv30) (칸 96)',
      pal=((232, 160, 136), (88, 88, 96)),
      tones=dict(white='shine', light='pink skin of the brain and body', dark='gray saucer', black='eyes, gaps'),
      keep=['A big pink brain-shaped dome on top of the head.', 'Two large yellow eyes with red pupils.', 'A thin pinkish body with thin arms; one hand holds a ray gun.', 'Sitting on a gray flying saucer.'],
      not_=['Not a little green alien.', 'No legs; the lower body sits in the saucer.'],
      keep_back=['The brain dome from behind.', 'The flat saucer under it.']),   # 불확실: 참고 그림이 wikimon 3D 모델(Vademon_Model_DW3)이라 2D 원화로 다시 확인
 dict(id='raremon', ko='레어몬', en='Raremon', grade='성숙기', tier=3, dir='raremon', wiki='Raremon',
      use='야생(야돈 우물) (칸 226)',
      pal=((120, 152, 216), (56, 64, 128)),
      tones=dict(white='teeth, eye shine', light='blue slime', dark='dark blue slime shadow', black='eyes, cracks'),
      keep=['A hunched zombie-like mass of blue dripping slime.', 'Red glowing eyes in a skull-like face with sharp teeth.', 'Long claws on both hands.', 'Dripping slime and a puff of yellow gas.'],
      not_=['No wings, no tail.', 'Not a ghost; a heavy melting body.'],
      keep_back=['The dripping blue slime back.', 'The hunched shoulders.']),
 dict(id='gesomon', ko='게소몬', en='Gesomon', grade='성숙기', tier=3, dir='gesomon', wiki='Gesomon',
      use='야생(바다) (칸 72)',
      pal=((248, 248, 248), (160, 56, 64)),
      tones=dict(white='white body', light='pale gray lines', dark='gray patterns', black='claws, tentacle tips, outline'),
      keep=['A white squid-like monster with a tall pointed head.', 'Dark tribal patterns on the head.', 'A wide mouth with sharp fangs and a red inside.', 'Many white tentacles with black curved claws.'],
      not_=['Not a cute squid.', 'No legs; only tentacles.'],
      keep_back=['The tall pointed head.', 'The trailing tentacles.']),
 dict(id='dokugumon', ko='도쿠구몬', en='Dokugumon', grade='성숙기', tier=3, dir='dokugumon', wiki='Dokugumon',
      use='야생(너도밤나무 숲 Lv20+·동굴) (칸 48)',
      pal=((56, 56, 64), (224, 64, 48)),
      tones=dict(white='skull marking', light='orange hair, gold horns', dark='black fur', black='outline'),
      keep=['A big black hairy spider body with a white skull mark on its back.', 'A fierce face with a spiky orange mane and yellow horns.', 'Many legs with red claws at the tips.'],
      not_=['Not a cute spider.', 'No spider web.'],
      keep_back=['The skull mark on the back.', 'The spiky orange mane.']),
 dict(id='pumpmon', ko='펌프몬', en='Pumpmon', grade='성숙기', tier=3, dir='pumpmon', wiki='Pumpmon',
      use='야생(자연 공원 밤) (칸 203)',
      pal=((248, 160, 40), (56, 128, 64)),
      tones=dict(white='ragdoll body', light='orange pumpkin', dark='dark orange shading, green cape', black='face carving, stitches'),
      keep=['A round orange pumpkin head with a glowing jack-o-lantern face.', 'An axe stuck in the top of the head.', 'A white soft ragdoll body with brown stitches.', 'A green scarf and a green ragged cape.'],
      not_=['Not a ghost.', 'No limbs other than the soft ragdoll ones.'],
      keep_back=['The axe on the head.', 'The green ragged cape.']),
 dict(id='flarelizarmon', ko='다크리자몬', en='Flare Lizarmon', grade='성숙기', tier=2, dir='flarelizarmon', wiki='Flare_Lizarmon',
      use='암흑단 (칸 58)',
      pal=((248, 160, 32), (120, 40, 24)),
      tones=dict(white='bright flame core', light='yellow-orange flames', dark='red-orange flames', black='steel head and claws, outline'),
      keep=['A lizard-like body made entirely of orange flames.', 'A gray steel mask covering the head with red eyes.', 'Long steel claws.', 'Flames rising from the back.'],
      not_=['Not a Greymon; it is a flame lizard.', 'No wings.'],
      keep_back=['The flame-covered back.', 'The steel head from behind.']),
 dict(id='mechanorimon', ko='메카노리몬', en='Mechanorimon', grade='성숙기', tier=3, dir='mechanorimon', wiki='Mechanorimon',
      use='암흑단(기계)·야생(라디오 타워) (칸 81)',
      pal=((200, 200, 208), (64, 72, 88)),
      tones=dict(white='metal highlights', light='light gray metal', dark='dark gray metal', black='joints, outline'),
      keep=['A gray robot with a blue glass dome on its head.', 'A round red lens in the chest.', 'Very long arms ending in large claw hands.', 'A big boxy torso with pipes on the back.'],
      not_=['Not a humanoid knight.', 'No weapons other than the arms.'],
      keep_back=['The pipes and boxes on the back.', 'The blue dome head.']),
 dict(id='hangyomon', ko='다이버몬', en='Hangyomon', grade='완전체', tier=2, dir='hangyomon', wiki='Hangyomon',
      use='사천왕 일목 파티·야생(41번 수로 깊은 곳 Lv40) (칸 73)',
      pal=((48, 88, 168), (224, 64, 56)),
      tones=dict(white='belly, harpoon tip', light='blue body', dark='dark blue shading, red fins', black='outline'),
      keep=['A blue fish-man with a big fish-like head.', 'Webbed hands with long claws.', 'A harpoon held in the hand.', 'A glowing light bulb lure hanging below and small red and white fins.'],
      not_=['Not a mermaid.', 'No armor.'],
      keep_back=['The red fins along the back.', 'The harpoon.']),
 dict(id='anomalocarimon', ko='스콜피오몬', en='Anomalocarimon', grade='완전체', tier=2, dir='anomalocarimon', wiki='Anomalocarimon',
      use='사천왕 일목 파티 (칸 98)',
      pal=((232, 200, 152), (168, 88, 48)),
      tones=dict(white='blade shine', light='tan shell', dark='brown segments, red marks', black='eyes, tips'),
      keep=['A tan segmented armored body with a skull-like head.', 'Two big black round eyes.', 'Many long steel blades fanning out on both sides.', 'A long curled segmented tail with a dark tip.'],
      not_=['No legs.', 'Not a plain scorpion.'],
      keep_back=['The segmented shell from behind.', 'The fan of blades.']),
 dict(id='gerbemon', ko='가베지몬', en='Gerbemon', grade='완전체', tier=2, dir='gerbemon', wiki='Gerbemon',
      use='사천왕 독수 파티 (칸 227)',
      pal=((232, 152, 168), (72, 104, 56)),
      tones=dict(white='teeth, lid markings', light='pink skin', dark='green garbage can', black='eyes, outline'),
      keep=['A pink goblin-like creature sitting in a green garbage can.', 'Messy yellow hair like a rotten banana top.', 'A big evil grin with large teeth.', 'A bazooka on the shoulder and a garbage can lid with glowing 01 marks.'],
      not_=['Not a clean character.', 'Not a robot.'],
      keep_back=['The garbage can from behind.', 'The bazooka over the shoulder.']),
 dict(id='floramon', ko='플로라몬', en='Floramon', grade='성장기', tier=3, dir='floramon', wiki='Floramon',
      use='야생(자연 공원·35번 도로) (칸 71)',
      pal=((248, 248, 216), (216, 56, 64)),
      tones=dict(white='cream belly', light='cream-yellow body', dark='purple petals and green legs', black='eyes, outline'),
      keep=['A small bird-like plant creature wearing a red flower-petal hood.', 'A pale yellow-cream round belly.', 'Large purple-and-white petal-shaped hands.', 'Green root-like legs and curly yellow vines.'],
      not_=['Not Palmon; the flower is a hood around the face.', 'No armor.'],
      keep_back=['The red petal hood from behind.', 'The purple petal feathers.']),
 dict(id='mushmon', ko='머슈룸몬', en='Mushmon', grade='성장기', tier=3, dir='mushmon', wiki='Mushmon',
      use='야생(숲) (칸 182)',
      pal=((176, 112, 208), (240, 208, 64)),
      tones=dict(white='cream face and body', light='cream body, purple cap', dark='purple cap shading, pink boots', black='outline, eyes'),
      keep=['A walking mushroom with a big purple cap with yellow rings.', 'A cream face with a toothy smile under the cap.', 'Big pink gloves, one with a skull mark, and big pink boots with buckles.', 'A tiny red mushroom at its feet.'],
      not_=['Not a cute child.', 'No weapons.'],
      keep_back=['The big ringed cap from behind.', 'The pink gloves and boots.']),
 dict(id='blossomon', ko='블로섬몬', en='Blossomon', grade='완전체', tier=2, dir='blossomon', wiki='Blossomon',
      use='사천왕 독수 파티 (칸 113)',
      pal=((112, 72, 176), (248, 232, 64)),
      tones=dict(white='yellow glow of the face', light='yellow face, red petals', dark='purple petals, green vines', black='face carving, outline'),
      keep=['A giant purple flower with a glowing yellow evil face in the center.', 'Many thick green vines acting as legs and tentacles.', 'Small red flowers with black angry faces on the vine ends.', 'Dark green leaves behind the flower.'],
      not_=['No humanoid body.', 'Not a cute flower.'],
      keep_back=['The purple petals from behind.', 'The green vines.']),
 dict(id='delumon', ko='데라몬', en='Delumon', grade='성숙기', tier=3, dir='delumon', wiki='Delumon',
      use='야생(43·44번 도로) (칸 85)',
      pal=((88, 128, 208), (48, 120, 64)),
      tones=dict(white='belly', light='light blue feathers, yellow beak', dark='green bush shell', black='eyes, outline'),
      keep=['A fat blue penguin-like bird with a big yellow beak.', 'A small gold crown on its head.', 'A red bow tie and red shoes.', 'A round green bush on its back with pink flowers.'],
      not_=['Not a real penguin; it has a bush on its back.', 'No spread wings.'],
      keep_back=['The big green bush with pink flowers.', 'The crown.']),
 dict(id='gigadramon', ko='기가드라몬', en='Gigadramon', grade='완전체', tier=2, dir='gigadramon', wiki='Gigadramon',
      use='사천왕 시바 파티 (칸 149)',
      pal=((136, 120, 168), (48, 56, 64)),
      tones=dict(white='steel shine', light='lavender dragon skin', dark='dark purple, gray armor', black='outline'),
      keep=['A purple cyborg dragon with a long serpent body.', 'Large steel blade-like plates fanning out from the back.', 'A mechanical armored head with sharp teeth.', 'Missile-like parts on the lower body.'],
      not_=['Not a western dragon with legs.', 'No fire.'],
      keep_back=['The steel plates from behind.', 'The long tail.']),
 dict(id='tankmon', ko='탱크몬', en='Tankmon', grade='성숙기', tier=2, dir='tankmon', wiki='Tankmon',
      use='암흑단(기계) (칸 82)',
      pal=((104, 128, 64), (64, 64, 64)),
      tones=dict(white='metal shine, teeth', light='olive green armor', dark='dark green shading, tracks', black='tracks, barrels'),
      keep=['A big olive green tank body with tracks.', 'Two cannon barrels on top, one large and one smaller.', 'A monstrous mouth with teeth on the front.', 'A spiked plow plate at the front and an ammo belt along the side.'],
      not_=['No legs.', 'Not a plain tank; it has a face.'],
      keep_back=['The turret and cannons.', 'The ammo belt.']),
 dict(id='warumonzaemon', ko='다크퍼펫몬', en='Waru Monzaemon', grade='완전체', tier=2, dir='warumonzaemon', wiki='Waru_Monzaemon',
      use='사천왕 시바 파티 (와루몬자에몬, 한국판 이름 확인되면 교체) (칸 216)',
      pal=((88, 88, 96), (216, 64, 56)),
      tones=dict(white='cream belly', light='gray fur', dark='dark gray patches and black armor', black='eyes, outline'),
      keep=['A big dark gray stitched teddy bear.', 'Glowing red eyes and a red scarf.', 'A metal armor plate strapped on one arm, with long claws.', 'A cream belly with a glowing green gem and cross stitches.'],
      not_=['Not cute and pink like Monzaemon.', 'No weapon other than claws.'],
      keep_back=['The red cape.', 'The stitched dark back.']),
 dict(id='parrotmon', ko='파롯트몬', en='Parrotmon', grade='완전체', tier=3, dir='parrotmon', wiki='Parrotmon',
      use='고정(첫 극장판, 알프의 유적 입구 Lv30) (칸 164)',
      pal=((64, 160, 88), (248, 216, 64)),
      tones=dict(white='shine', light='green body', dark='dark green shading', black='eyes, claws'),
      keep=['A large green parrot-like bird with a silver metal beak mask.', 'Yellow wing feathers.', 'Red feather plumes on the head.', 'Strong teal legs with big claws.'],
      not_=['No arms; wings only.', 'Not a phoenix.'],
      keep_back=['The yellow wing feathers.', 'The red head plumes.']),
 dict(id='kuramon', ko='쿠라몬', en='Kuramon', grade='유아기Ⅰ', tier=0, dir='kuramon', wiki='Kuramon',
      use='디아블로몬의 역습 이벤트(2부)',
      pal=((200, 208, 248), (88, 96, 176)),
      tones=dict(white='shine', light='pale lavender body', dark='lavender shading', black='outline, pupil'),
      keep=['A pale lavender star-shaped round body with soft points.', 'ONE huge round orange eye with a dark pupil.', 'No mouth, no arms, no legs.'],
      not_=['No arms, no legs, no mouth.', 'Not two eyes.'],
      keep_back=['The smooth star-shaped back (no eye).']),
 dict(id='tsumemon', ko='츠메몬', en='Tsumemon', grade='유년기Ⅱ', tier=0, dir='tsumemon', wiki='Tsumemon',
      use='디아블로몬의 역습 이벤트(2부)',
      pal=((184, 184, 240), (96, 88, 168)),
      tones=dict(white='claws, eye shine', light='pale lavender body', dark='violet shading', black='pupil, outline'),
      keep=['A round lavender body with ONE big orange eye.', 'A long thin curved antenna on top.', 'Thick pale claws at the front.'],
      not_=['No arms, no mouth.', 'Not two eyes.'],
      keep_back=['The antenna on top.', 'The round lavender back.']),
 dict(id='chrysalimon', ko='크리사리몬', en='Chrysalimon', grade='성숙기', tier=0, dir='chrysalimon', wiki='Chrysalimon',
      use='디아블로몬의 역습 이벤트(2부)',
      pal=((152, 120, 200), (232, 224, 168)),
      tones=dict(white='bone-colored spikes', light='purple shell', dark='dark purple shading', black='outline'),
      keep=['A purple armored chrysalis body with a pointed top.', 'A red horn on the front of the head.', 'Yellow-white curved spikes at the sides.', 'Thin black whip-like tendrils.'],
      not_=['No arms, no legs.', 'Not a butterfly.'],
      keep_back=['The pointed shell from behind.', 'The curved spikes.']),
 dict(id='armagemon', ko='아마게몬', en='Armagemon', grade='궁극체', tier=0, dir='armagemon', wiki='Armagemon',
      use='2부 이벤트 보스(보류)',
      pal=((104, 96, 120), (40, 32, 48)),
      tones=dict(white='faint metal shine', light='dark purple-gray armor', dark='black shell', black='outline'),
      keep=['A flat black armored insect-like body.', 'Very long thin jointed legs ending in sharp points.', 'A long curved segmented tail.', 'A small angry face at the front.'],
      not_=['Not humanoid.', 'No wings.'],
      keep_back=['The flat armored back.', 'The legs spread out.']),
 dict(id='airdramon', ko='에어드라몬', en='Airdramon', grade='성숙기', tier=3, dir='airdramon', wiki='Airdramon',
      use='야생 37·42번 도로 Lv20+ (칸 142)',
      pal=((232, 96, 48), (40, 104, 168)),
      tones=dict(white='skull face, bone', light='orange wing', dark='blue serpent body', black='black wing part, outline'),
      keep=['A long blue snake-like dragon body coiling at the bottom.', 'A bony skull-like white face with a yellow and red mane.', 'Large tattered bat-like wings, orange on one side and black on the other.', 'No legs.'],
      not_=['No arms or legs.', 'Not a western dragon.'],
      keep_back=['The big tattered wings.', 'The coiled blue tail with a fiery tip.']),
 dict(id='coelamon', ko='실러캔몬', en='Coelamon', grade='성숙기', tier=3, dir='coelamon', wiki='Coelamon',
      use='야생 낚시(41번 수로·소용돌이 섬) Lv20+ (칸 138)',
      pal=((232, 232, 232), (88, 104, 152)),
      tones=dict(white='bone-white skull and fins', light='gray bone', dark='gray shading, pink scales', black='outline'),
      keep=['A skeletal coelacanth fish with a bony white skull head.', 'One big blue eye.', 'A wide open mouth with sharp teeth.', 'Pink scales on the lower body and pale blue fins.'],
      not_=['No legs.', 'Not a normal fish.'],
      keep_back=['The bony ridge on the back.', 'The fins and tail.']),
 dict(id='gizamon', ko='기자몬', en='Gizamon', grade='성장기', tier=3, dir='gizamon', wiki='Gizamon',
      use='야생 물가(32번 도로·연분홍) Lv5~15 (칸 54)',
      pal=((248, 216, 48), (216, 64, 32)),
      tones=dict(white='fang and claw shine', light='yellow body', dark='orange-red mane', black='steel back blades, claw tips'),
      keep=['A yellow four-legged lizard-like beast.', 'A spiky red-orange mane from head to tail.', 'Large steel blades along the back.', 'Steel claws on all four feet and a blue eye with small fangs.'],
      not_=['No wings.', 'Not a cute puppy.'],
      keep_back=['The row of steel blades.', 'The red mane and tail.']),
 dict(id='otamamon', ko='오타마몬', en='Otamamon', grade='성장기', tier=3, dir='otamamon', wiki='Otamamon',
      use='야생 물(야돈 우물·호수) Lv5~15 (칸 79)',
      pal=((72, 72, 176), (168, 176, 216)),
      tones=dict(white='eye whites, claw tips', light='blue body', dark='dark blue shading', black='pupils, outline'),
      keep=['A round dark-blue body shaped like a big tadpole.', 'Two big round eyes with large black pupils.', 'A short flat tail with a pale finned tip.', 'Small clawed hands and feet.'],
      not_=['Not a fish with scales.', 'No clothes.'],
      keep_back=['The round blue back.', 'The tail with the pale tip.']),
 dict(id='ganimon', ko='가니몬', en='Ganimon', grade='성장기', tier=3, dir='ganimon', wiki='Ganimon',
      use='야생 바닷가(40번 수로) Lv5~15 (칸 99)',
      pal=((152, 168, 200), (200, 72, 72)),
      tones=dict(white='shine', light='light blue-gray shell', dark='gray-blue shading', black='outline, claw edges'),
      keep=['A small crab-like body in gray-blue armor.', 'Red spots on the shell.', 'Green eyes on a pointed head.', 'Thin long arms with pincers and a curved tail.'],
      not_=['Not a red crab.', 'No wings.'],
      keep_back=['The red-spotted shell.', 'The curled tail.']),
 dict(id='evilmon', ko='이비르몬', en='Evilmon', grade='성숙기', tier=2, dir='evilmon', wiki='Evilmon',
      use='암흑단 조직원 (칸 207)',
      pal=((88, 112, 104), (216, 72, 40)),
      tones=dict(white='fangs, chest fur', light='gray-green skin', dark='dark green shading', black='eyes, outline'),
      keep=['A gray-green devil with a wide open red mouth and sharp fangs.', 'Spiky red hair on the head.', 'Two large bat wings with dark membranes.', 'Long orange claws on hands and feet.'],
      not_=['Not Devimon; no hood and no armor.', 'No weapon.'],
      keep_back=['The big wings from behind.', 'The red spiky hair.']),
 dict(id='deathmeramon', ko='데스메라몬', en='Death Meramon', grade='완전체', tier=2, dir='deathmeramon', wiki='Death_Meramon',
      use='암흑단 아지트 간부 파티 (칸 219)',
      pal=((80, 152, 216), (224, 96, 24)),
      tones=dict(white='ice-white chain shine', light='pale skin and ice flames', dark='black pants and hair, flame', black='boots, hair, outline'),
      keep=['A tall muscular man with spiky black hair and a bare chest.', 'Heavy silver chains wrapped around both arms.', 'Pale blue-white flames around the chains.', 'Black pants with orange flame patterns and striped boots with skull toes.'],
      not_=['Not a fire elemental made of orange flame.', 'No weapon other than chains.'],
      keep_back=['The chains across the back.', 'The spiky black hair.']),
 dict(id='giromon', ko='지로몬', en='Giromon', grade='완전체', tier=2, dir='giromon', wiki='Giromon',
      use='시바 파티 (칸 213)',
      pal=((72, 72, 168), (216, 56, 48)),
      tones=dict(white='metal shine, teeth', light='blue metal', dark='dark blue', black='gaps, outline'),
      keep=['A round blue metal ball head with two curved horns.', 'Angry red eyes and a sharp-toothed grin.', 'One arm ending in a chainsaw.', 'The other hand holding a red spiked bomb.'],
      not_=['No legs.', 'Not a cute robot.'],
      keep_back=['The two horns.', 'The round metal back of the head.']),
 dict(id='piccolomon', ko='피콜로몬', en='Piccolomon', grade='완전체', tier=3, dir='piccolomon', wiki='Piccolomon',
      use='고정 만남(자연 공원 숨은 방 Lv30, 포획 30) (칸 183)',
      pal=((248, 128, 176), (248, 248, 248)),
      tones=dict(white='wings, spear shine', light='pink fur', dark='pink shading', black='outline, spear tip'),
      keep=['A small pink monkey-like fairy with a pale round face.', 'Large thin white wings with red stitch marks.', 'A long spear held across the body.', 'Bare small hands and feet.'],
      not_=['Not an angel; no halo.', 'No clothes.'],
      keep_back=['The big white wings.', 'The pink round back.']),
]

DIGIVICE = dict(id='digivice', ko='디지바이스', en='Digivice', grade='도구', tier=1, dir='', wiki='',
                use='공박사 연구소에서 볼 대신 고르는 스타팅 선택 물건 — 롬에 넣음')

PX = {'유아기Ⅰ': 30, '유아기Ⅱ': 30, '유년기Ⅰ': 30, '유년기Ⅱ': 30, '성장기': 40}
def px(grade): return PX.get(grade, 50)

def by_id(did):
    return next((s for s in S if s['id'] == did), None)
