"""그림 주문서 v3 종별 값 (gen_order.py 가 읽음, ingest.py 가 pal·등급을 읽음)
 tier 1 = 지금 막힌 것 / 2 = 보스·암흑단·암흑 진화 / 3 = 갈래·유아기 / 0 = 후보(결정 대기)
 tones: 받을 그림의 회색 4톤이 각각 어느 부위인지. pal: 롬에 넣을 때 입힐 밝은·어두운 색 (흰색·검정은 고정)
 keep: 1번이 가장 중요. not: 그 종이 잘못 그려지는 방향을 미리 막음. keep_back: 뒤에서 보이는 것만
 wiki: 위키몬 문서 이름 (LCD 도트 찾기, lcd.json)"""

S = [
 # ── 1 지금 막힌 것 ──
 dict(id='metalgreymon', ko='메탈그레이몬', en='MetalGreymon', grade='완전체', tier=1, dir='metalgreymon-v', wiki='MetalGreymon', front_done=True,
      use='그레이몬 →(용기 문장) 메탈그레이몬 → 워그레이몬. 앞모습은 롬에 들어감 — 뒷모습만 다시',
      pal=((232, 128, 48), (96, 112, 136)),
      tones=dict(white='metal highlights', light='orange skin', dark='metal arm, helmet, chest plate, wings', black='outline, eyes, claws'),
      keep=['A huge silver metal LEFT arm with three long claws (the character\'s own left arm).',
            'A metal helmet covering the upper face, with one horn.',
            'A metal chest plate.',
            'Two torn purple bat-like wings on the back.',
            'Orange dinosaur body with blue stripes and a thick tail.'],
      not_=['Do not put the metal arm on the character\'s right arm.'],
      keep_back=['The big metal LEFT arm, on the LEFT side of the image in this rear view, with its three claws.',
                 'The two torn wings spread from the back.',
                 'The horned metal helmet seen from behind, one horn tip visible.',
                 'The thick tail at the bottom edge.'],
      not_back=['Do not put the metal arm on the right side of the image.']),
 dict(id='weregarurumon', ko='워가루몬', en='WereGarurumon', grade='완전체', tier=1, dir='weregarrumon', wiki='WereGarurumon',
      use='가루몬 →(우정 문장) 워가루몬 → 메탈가루몬. 지금은 물음표 알',
      pal=((136, 184, 240), (40, 72, 160)),
      tones=dict(white='white fur, bandages on the fists', light='blue fur patches, the mane, the jeans', dark='belts, shoulder strap, spiked shoulder pad', black='claws'),
      keep=['A muscular werewolf standing upright on two legs.',
            'A big spiky mane around the head and shoulders.',
            'Ripped jeans; one strap crossing the chest with a spiked shoulder pad on one shoulder.',
            'Bandaged fists with big claws.'],
      not_=['Not a four-legged wolf.', 'No skull emblem, no small stitches, no fur stripes smaller than a few pixels.'],
      keep_back=['The spiky mane from behind.', 'The strap crossing the back.', 'The spiked pad on the right shoulder.', 'The tail.']),
 dict(id='tunomon', ko='뿔몬', en='Tsunomon', grade='유년기Ⅱ', tier=1, dir='tunomon', wiki='Tunomon',
      use='29~32번 도로 야생 (러브리몬 칸) → Lv11 파피몬',
      pal=((232, 168, 96), (128, 72, 40)),
      tones=dict(white='the face', light='orange-brown fur', dark='the horn, fur shading', black='eyes'),
      keep=['ONE long curved horn growing from the top of the head.',
            'A round ball body with NO arms and NO legs.',
            'Shaggy fur around the face, the face is pale.',
            'Big round eyes, small open mouth.'],
      not_=['No arms, no legs, no feet.', 'Only one horn, not two.'],
      keep_back=['The round furry back.', 'The horn sticking up above the head.']),
 dict(id='tokomon', ko='토코몬', en='Tokomon', grade='유년기Ⅱ', tier=1, dir='tokomon', wiki='Tokomon',
      use='29~31번 도로 밤 야생 (팔코몬 칸) + 공박사 조수의 알 → Lv10 파닥몬',
      pal=((248, 184, 192), (200, 64, 72)),
      tones=dict(white='the round body', light='inside of the ears, cheeks', dark='inside of the mouth, eyes', black='outline'),
      keep=['A tiny round white body like a marshmallow.',
            'Two long thin ear-feelers on top of the head.',
            'Two very short stubby feet and two tiny arms.',
            'Small red eyes, a small mouth.'],
      not_=['No tail, no wings.', 'Not a rabbit or a hamster.'],
      keep_back=['The round white back.', 'The two ear-feelers.', 'The stubby feet at the bottom.']),
 dict(id='pyocomon', ko='어니몬', en='Yokomon', grade='유년기Ⅱ', tier=1, dir='pyocomon', wiki='Pyocomon',
      use='32·33번 도로 야생 (통통코 칸) → Lv12 피요몬',
      pal=((248, 184, 200), (64, 104, 200)),
      tones=dict(white='highlight on the body', light='pale pink bulb body', dark='the big flower on the head', black='eyes'),
      keep=['A large flower with wide petals on top of the head, almost as wide as the body.',
            'An onion-bulb body with NO arms and NO legs, a few tiny root stubs at the bottom.',
            'A curly stamen rising from the center of the flower.',
            'Small eyes and a tiny mouth.'],
      not_=['No arms, no legs.', 'Not a potted plant.'],
      keep_back=['The flower seen from behind on top.', 'The round bulb back.', 'The root stubs at the bottom.']),
 dict(id='mochimon', ko='모티몬', en='Motimon', grade='유년기Ⅱ', tier=1, dir='mochimon', wiki='Mochimon',
      use='32번 도로 야생 (메리프 칸) → Lv12 텐타몬',
      pal=((248, 192, 208), (176, 88, 120)),
      tones=dict(white='highlights', light='soft pink body', dark='inside of the mouth, the tiny claws', black='eyes'),
      keep=['A soft pink rice-cake body shaped like a little ghost, the bottom edge is wavy, NO legs.',
            'Two stubby arms, each with tiny dark claws.',
            'Big round black eyes.',
            'An open happy mouth.'],
      not_=['No legs, no tail.', 'Not a flat slime puddle.'],
      keep_back=['The rounded back.', 'The wavy bottom edge.', 'The stubby arms at the sides.']),
 dict(id='tanemon', ko='시드몬', en='Tanemon', grade='유년기Ⅱ', tier=1, dir='tanemon', wiki='Tanemon',
      use='너도밤나무 숲 야생 (파라스 칸) → Lv11 팔몬',
      pal=((168, 216, 104), (48, 120, 56)),
      tones=dict(white='the cream face', light='green top of the bulb', dark='the leaves, the little feet', black='eyes'),
      keep=['An onion-bulb body: green on top, cream face below.',
            'Two long leaves sprouting from the top of the head.',
            'Four tiny root-like feet under the body.',
            'Big eyes, a small cat-like mouth.'],
      not_=['No arms.', 'Not a frog.'],
      keep_back=['The green bulb back.', 'The leaves on top.', 'The little feet at the bottom.']),
 dict(id='pukamon', ko='둥실몬', en='Bukamon', grade='유년기Ⅱ', tier=1, dir='pukamon', wiki='Pukamon',
      use='낚시 (콘치 칸) → Lv13 쉬라몬',
      pal=((184, 192, 208), (232, 96, 40)),
      tones=dict(white='belly, inside of the mouth', light='gray body, flippers', dark='the flame tuft on the head, tail fin shading', black='eyes'),
      keep=['A big HEAVY LOWER JAW: the mouth is the widest part of the head and sticks out forward.',
            'NO LEGS. A plump seal-like baby with two front flippers and a fish tail.',
            'A flame-shaped tuft of hair on top of the head.',
            'A round body, almost as wide as tall.'],
      not_=['No legs, no feet, no arms with fingers.', 'No wings.'],
      keep_back=['The round back.', 'The flame tuft on top.', 'The tail fin at the bottom edge.', 'The flippers at the sides.']),
 dict(id='gazimon', ko='가지몬', en='Gazimon', grade='성장기', tier=1, dir='gazimon', wiki='Gazimon',
      use='어둠의 동굴 야생 (노고치 칸)',
      pal=((184, 180, 200), (88, 80, 120)),
      tones=dict(white='muzzle and belly', light='gray fur', dark='stripes on the ears and back', black='claws, eyes'),
      keep=['Very long rabbit-like ears with dark stripes.',
            'Stands on two legs in a hunched, sly pose.',
            'Long sharp claws on both hands.',
            'A sly grin with sharp teeth, red eyes.'],
      not_=['Not a cute bunny.', 'No clothes, no wings.'],
      keep_back=['The long striped ears.', 'The striped back.', 'The claws at the sides.']),
 dict(id='bakemon', ko='고스몬', en='Bakemon', grade='성숙기', tier=1, dir='bakemon', wiki='Bakemon',
      use='모다피의 탑·암흑단 조직원 (임프몬 칸)',
      pal=((200, 200, 216), (56, 48, 80)),
      tones=dict(white='the sheet (most of the body)', light='folds and shading on the sheet', dark='the dark hole where the face is', black='eyes, teeth'),
      keep=['A floating ghost wearing a plain white sheet; the sheet is the whole body.',
            'A large dark opening in the sheet where the face would be, with two glowing eyes and a row of sharp teeth inside it.',
            'Two clawed hands coming out of the sheet at the sides.',
            'The bottom of the sheet is a wavy tail, no legs.'],
      not_=['No legs, no feet.', 'No hat, no horns, no wings.', 'Not a solid-body creature; it must read as a cloth sheet.'],
      keep_back=['The sheet seen from behind with its wavy bottom.', 'One claw peeking at the side.', 'No face.']),
 dict(id='kuwagamon', ko='쿠가몬', en='Kuwagamon', grade='성숙기', tier=1, dir='kuwagamon', wiki='Kuwagamon',
      use='36번 도로 길막 보스 (꼬지모 칸 185) · 텐타몬 유대 낮음 갈래',
      pal=((224, 64, 48), (88, 88, 104)),
      tones=dict(white='belly plates, inner edges of the pincers', light='red shell (head, back, limbs)', dark='wing membranes, joints, deep shadow under the shell', black='eyes, mouth'),
      keep=['Two HUGE stag-beetle pincers growing from the head, each longer than the head itself, with jagged inner edges.',
            'A long red beetle body standing upright on two legs, with FOUR thin arms on the torso.',
            'Four insect wings on the back.',
            'A toothy mouth between the pincers.'],
      not_=['Do not shrink the pincers into small horns.', 'Do not give it a round bulky bug body or stubby arms.', 'Do not add features from other monsters.'],
      keep_back=['Wings covering the back.', 'Pincer tips visible above the head.', 'Thin arms at the sides.']),
 dict(id='shellmon', ko='쉘몬', en='Shellmon', grade='성숙기', tier=1, dir='shellmon', wiki='Shellmon',
      use='낚시꾼·바닷가 트레이너, 사천왕 일목 (셀러 칸)',
      pal=((240, 144, 168), (80, 104, 136)),
      tones=dict(white='shell highlights, teeth', light='pink skin', dark='the gray-blue shell, the green hair', black='eyes'),
      keep=['A big spiked conch shell carried on its back behind the head, like a hermit crab. The shell does NOT cover the whole body.',
            'A pink, low, dinosaur-like body crawling on four short legs.',
            'Seaweed-like hair sticking out on top of the head.',
            'An open mouth with small teeth.'],
      not_=['Not a snail hiding inside its shell.', 'Not a turtle.', 'No tentacles.'],
      keep_back=['The big spiked shell from behind.', 'The hair tufts.', 'The short legs at the sides.']),
 dict(id='monochromon', ko='모노크로몬', en='Monochromon', grade='성숙기', tier=1, dir='monochromon', wiki='Monochromon',
      use='등산가 트레이너, 사천왕 시바 (롱스톤 칸)',
      pal=((176, 176, 184), (72, 72, 88)),
      tones=dict(white='horn and beak highlights', light='gray body', dark='the dark armor plates on the head frill and back', black='eyes'),
      keep=['ONE long horn on the nose.',
            'A big triceratops-like frill behind the head.',
            'A heavy four-legged dinosaur body with armor plates on the back.',
            'Small eyes and a beak-like mouth.'],
      not_=['Not two or three horns.', 'Not standing upright.'],
      keep_back=['The frill and back plates from behind.', 'The horn tip visible past the head.', 'The thick legs.']),
 dict(id='numemon', ko='워매몬', en='Numemon', grade='성숙기', tier=1, dir='numemon', wiki='Numemon',
      use='초반 트레이너, 사천왕 독수 (질퍽이 칸)',
      pal=((176, 208, 96), (136, 64, 152)),
      tones=dict(white='teeth, eye whites', light='green slug body', dark='the tongue, the spots', black='pupils'),
      keep=['Two eyes on long stalks, bloodshot.',
            'A huge mouth with big teeth and the tongue sticking out.',
            'A slug body with NO arms and NO legs.',
            'Spots on the body.'],
      not_=['No arms, no legs.', 'No snail shell.'],
      keep_back=['The slimy hump.', 'The two eye stalks above it.']),
 dict(id='seadramon', ko='시드라몬', en='Seadramon', grade='성숙기', tier=1, dir='seadramon', wiki='Seadramon',
      use='베타몬 → 시드라몬 → 메가시라몬 줄, 쉬라몬 유대 낮음 갈래 (왕콘치 칸)',
      pal=((240, 216, 96), (48, 144, 160)),
      tones=dict(white='teeth, eye shine', light='the yellow mask and belly', dark='the teal body, the tail fin', black='eyes'),
      keep=['A long sea-serpent body coiled in an S shape, NO arms and NO legs.',
            'A yellow helmet-like mask covering the top of the head, with a crest.',
            'Long jaws.',
            'A fin at the tip of the tail.'],
      not_=['No legs, no arms, no wings.', 'Not a whiskered Chinese dragon.'],
      keep_back=['The coiled body.', 'The back of the mask.', 'The tail fin.']),
 dict(id='centalmon', ko='켄터스몬', en='Centarumon', grade='성숙기', tier=1, dir='centalmon', wiki='Centalmon',
      use='초반 트레이너, 사천왕 시바 (켄타로스 칸)',
      pal=((216, 176, 120), (64, 96, 176)),
      tones=dict(white='armor highlights', light='the tan horse body and skin', dark='the blue armor plates and helmet', black='the eye'),
      keep=['A centaur: a humanoid upper body on a four-legged horse body.',
            'A helmet with ONE eye.',
            'An arm cannon on one arm.',
            'Blue armor plates on the shoulders and chest.'],
      not_=['No wings.', 'Not a plain horse.'],
      keep_back=['The armored back.', 'The four legs.', 'The arm cannon at one side.']),
 # ── 2 보스·암흑단·암흑 진화 ──
 dict(id='vamdemon', ko='묘티스몬', en='Myotismon', grade='완전체', tier=2, dir='vamdemon', wiki='Vamdemon',
      use='암흑단 우두머리 (라디오 타워 꼭대기), 크로뱃 칸',
      pal=((216, 64, 64), (48, 48, 104)),
      tones=dict(white='pale face and hair', light='red bat mask, red cape lining', dark='dark suit, outside of the cape', black='eyes'),
      keep=['A tall vampire lord with a huge cape spreading out behind him.',
            'A red bat-shaped mask over the eyes.',
            'A dark suit with a high collar.',
            'Long thin arms with claws.'],
      not_=['Not a bat monster.', 'No wings (only the cape).', 'No horns.'],
      keep_back=['The cape covering the back.', 'The high collar.', 'The hair.']),
 dict(id='fantomon', ko='팬텀몬', en='Phantomon', grade='완전체', tier=2, dir='fantomon', wiki='Fantomon',
      use='암흑단 간부 (아지트)',
      pal=((200, 184, 232), (64, 48, 96)),
      tones=dict(white='the skull face, bony hands', light='light parts of the cloak', dark='the dark hooded cloak', black='eye holes'),
      keep=['A floating grim reaper in a ragged hooded cloak, no legs.',
            'A big scythe.',
            'A skull-like face inside the hood.',
            'Bony hands.'],
      not_=['No legs, no wings.', 'Not a knight in armor.'],
      keep_back=['The hood and ragged cloak from behind.', 'The scythe blade above the shoulder.']),
 dict(id='devidramon', ko='데블드라몬', en='Devidramon', grade='성숙기', tier=2, dir='devidramon', wiki='Devidramon',
      use='암흑단 간부 (아지트)',
      pal=((200, 64, 64), (56, 40, 64)),
      tones=dict(white='claw tips, teeth', light='red eyes and wing membranes', dark='the dark body', black='outline'),
      keep=['FOUR glowing eyes.',
            'Huge bat-like wings.',
            'Very long arms with big claws.',
            'A dark dragon body.'],
      not_=['Not a two-eyed dragon.', 'Not a Western dragon breathing fire.'],
      keep_back=['The wings spread from the back.', 'The long arms at the sides.']),
 dict(id='skullgreymon', ko='스컬그레이몬', en='SkullGreymon', grade='완전체', tier=2, dir='skullgreymon', wiki='SkullGreymon',
      use='그레이몬 암흑 진화 (유대 낮음 + 자기 문장 없음)',
      pal=((232, 224, 200), (120, 112, 96)),
      tones=dict(white='bone highlights', light='bones', dark='the missile, shadows inside the ribcage', black='eye holes'),
      keep=['A dinosaur skeleton made of bare bones: skull head, ribcage, bony limbs.',
            'A big missile mounted along its back.',
            'A hunched, aggressive pose with a long bony tail.',
            'Glowing eyes in the skull.'],
      not_=['No flesh or skin.', 'Not a living dinosaur.'],
      keep_back=['The spine and the missile on it.', 'The bony tail.']),
 dict(id='ladydevimon', ko='레이디데블몬', en='LadyDevimon', grade='완전체', tier=2, dir='ladydevimon', wiki='LadyDevimon',
      use='가트몬 암흑 진화, 사천왕 카렌',
      pal=((200, 200, 216), (64, 40, 72)),
      tones=dict(white='pale skin', light='silver hair', dark='the black outfit and wings', black='outline'),
      keep=['A slim female demon in a tight black outfit.',
            'Huge tattered bat wings.',
            'A mask over the eyes and long silver hair.',
            'Long claws.'],
      not_=['Not an angel.', 'No horns on the head.'],
      keep_back=['The tattered wings.', 'The long hair from behind.']),
 dict(id='angewomon', ko='엔젤우몬', en='Angewomon', grade='완전체', tier=2, dir='angewomon', wiki='Angewomon',
      use='가트몬 →(빛 문장) 엔젤우몬, 레드(태일) 파티',
      pal=((248, 216, 112), (208, 104, 152)),
      tones=dict(white='wings and bodysuit', light='blond hair', dark='the ribbon sash and helmet', black='outline'),
      keep=['A female angel with EIGHT white wings.',
            'A helmet that covers her eyes.',
            'Long blond hair.',
            'A long ribbon sash floating around her.'],
      not_=['No halo, no sword.', 'Not a child.'],
      keep_back=['Eight wings from behind.', 'Long hair.', 'The ribbon sash.']),
 dict(id='monzaemon', ko='퍼펫몬', en='Monzaemon', grade='완전체', tier=2, dir='monzaemon', wiki='Monzaemon',
      use='관동 길막 (잠만보 칸) — 잠든 거대한 인형, 라디오로 깨움',
      pal=((248, 208, 72), (176, 120, 40)),
      tones=dict(white='the round belly', light='yellow fur', dark='paws, ears, shading', black='eyes'),
      keep=['A giant teddy bear.',
            'A big white round belly.',
            'Small round ears and small black eyes.',
            'Short thick arms and legs.'],
      not_=['Not a real bear; it is a stuffed toy.', 'No clothes.'],
      keep_back=['The round back.', 'The small ears.']),
 dict(id='metalseadramon', ko='메탈시드라몬', en='MetalSeadramon', grade='궁극체', tier=2, dir='metalseadramon', wiki='MetalSeadramon',
      use='사천왕 일목의 에이스 (어둠의 4천왕)',
      pal=((232, 208, 96), (112, 128, 160)),
      tones=dict(white='metal highlights', light='gold armor plates', dark='silver armor, the mane', black='eyes'),
      keep=['A long sea serpent covered in shiny metal armor, coiled in an S shape.',
            'A pointed metal head with a cannon on the nose.',
            'A wild mane behind the head.',
            'NO arms and NO legs.'],
      not_=['No legs, no arms.', 'Not a fish.'],
      keep_back=['The armored coils.', 'The mane.']),
 dict(id='mugendramon', ko='파워드라몬', en='Machinedramon', grade='궁극체', tier=2, dir='mugendramon', wiki='Mugendramon',
      use='사천왕 시바의 에이스 (어둠의 4천왕)',
      pal=((176, 176, 192), (72, 72, 88)),
      tones=dict(white='metal highlights', light='light metal parts', dark='dark metal body', black='eyes'),
      keep=['TWO huge round cannons mounted on its back over the shoulders.',
            'A gigantic dinosaur made entirely of metal.',
            'A mechanical jaw with red eyes.',
            'Big metal claws on hands and feet.'],
      not_=['No wings.', 'Not a robot humanoid.'],
      keep_back=['The two cannons on the back.', 'The tail.']),
 dict(id='pinochimon', ko='피노키몬', en='Puppetmon', grade='궁극체', tier=2, dir='pinochimon', wiki='Pinochimon',
      use='사천왕 독수의 에이스 (어둠의 4천왕)',
      pal=((232, 168, 104), (200, 56, 56)),
      tones=dict(white='gloves', light='wooden face and body', dark='the pointed hat, clothes', black='eyes'),
      keep=['A wooden puppet boy with a long wooden nose.',
            'A giant wooden hammer.',
            'A pointed hat.',
            'A wooden cross on his back with puppet strings.'],
      not_=['Not a real child.', 'No wings.'],
      keep_back=['The wooden cross and strings on the back.', 'The hammer over the shoulder.']),
 dict(id='apocalymon', ko='아포카리몬', en='Apocalymon', grade='궁극체', tier=2, dir='apoclymon', wiki='Apocalymon',
      use='챔피언(목호)의 에이스, 마지막 적',
      pal=((232, 200, 80), (48, 56, 112)),
      tones=dict(white='highlights', light='gold edges', dark='the dark many-sided body', black='outline'),
      keep=['A many-sided crystal-like body with gold edges, a point at the bottom.',
            'A small dark head on top.',
            'Long chains coming out of it, ending in spiked balls and claws.',
            'NO arms and NO legs.'],
      not_=['No legs.', 'Not a humanoid.'],
      keep_back=['The many-sided body from behind.', 'Chains at the sides.']),
 # ── 3 갈래·유아기 ──
 dict(id='tyranomon', ko='티라노몬', en='Tyrannomon', grade='성숙기', tier=3, dir='tyranomon', wiki='Tyranomon',
      use='아구몬 유대 낮음 갈래 (파라섹트 칸)',
      pal=((232, 96, 72), (64, 144, 72)),
      tones=dict(white='belly', light='red body', dark='green back spikes', black='eyes, claws'),
      keep=['A red tyrannosaurus standing on two strong legs.', 'A white belly.', 'Spikes along its back.', 'Short arms with big claws.'],
      not_=['No armor, no helmet.', 'Not orange like Greymon; no horns.'],
      keep_back=['The back spikes.', 'The thick tail.']),
 dict(id='vegimon', ko='베지몬', en='Vegiemon', grade='성숙기', tier=3, dir='vegimon', wiki='Vegimon',
      use='팔몬 유대 낮음 갈래 (덩구리 칸)',
      pal=((168, 208, 88), (120, 64, 152)),
      tones=dict(white='teeth', light='green body', dark='petals on top, vine shading', black='eyes'),
      keep=['A round green plant body.', 'A big mouth like a flytrap with sharp teeth.', 'A crown of petals on top.', 'Long vine arms.'],
      not_=['No legs with feet.', 'Not a cute flower.'],
      keep_back=['The petal crown.', 'The vine arms.']),
 dict(id='kiwimon', ko='키위몬', en='Kiwimon', grade='성숙기', tier=3, dir='kiwimon', wiki='Kiwimon',
      use='피요몬 유대 낮음 갈래 (두두 칸)',
      pal=((136, 200, 96), (152, 104, 64)),
      tones=dict(white='the white body', light='green feather crest', dark='brown lower body, legs', black='eyes'),
      keep=['A kiwi bird with a long beak.', 'A spiky crest of feathers on the head.', 'Long legs with claws.', 'NO wings.'],
      not_=['No wings.', 'Not a chicken.'],
      keep_back=['The feather crest.', 'The round back.']),
 dict(id='botamon', ko='깜몬', en='Botamon', grade='유아기Ⅰ', tier=3, dir='botamon', wiki='Botamon',
      use='알 전용 → 코로몬',
      pal=((240, 216, 72), (64, 64, 72)),
      tones=dict(white='eye shine', light='the yellow eyes', dark='the black fuzzy body', black='outline'),
      keep=['ONE round fuzzy ball covered in short spiky fur.', 'Two small ear bumps on top.', 'Two glowing yellow eyes.', 'No mouth, no arms, no legs.'],
      not_=['No arms, no legs, no tail.'],
      keep_back=['The fuzzy round back.', 'The ear bumps.']),
 dict(id='punimon', ko='푸니몬', en='Punimon', grade='유아기Ⅰ', tier=3, dir='punimon', wiki='Punimon',
      use='알 전용 → 뿔몬',
      pal=((232, 80, 80), (152, 32, 48)),
      tones=dict(white='big eyes', light='red jelly body', dark='shading', black='pupils'),
      keep=['A shiny red jelly dome.', 'Short rounded horn bumps on top.', 'Two big round eyes.', 'No arms, no legs.'],
      not_=['No arms, no legs, no spikes.'],
      keep_back=['The jelly dome back.', 'The horn bumps.']),
 dict(id='nyaromon', ko='야옹몬', en='Nyaromon', grade='유년기Ⅱ', tier=3, dir='nyaromon', wiki='Nyaromon',
      use='알 전용 → 플롯트몬',
      pal=((248, 224, 104), (152, 96, 176)),
      tones=dict(white='eye shine', light='yellow head', dark='tail stripes and tip, inside of the ears', black='eyes'),
      keep=['A round cat head with NO body.', 'Two big pointed cat ears.', 'One long striped tail coming out of the back of the head.', 'No arms, no legs.'],
      not_=['No body, no legs.'],
      keep_back=['The back of the head with the ears.', 'The striped tail.']),
 # ── 0 후보 (계획 결정 뒤 주문) ──
 dict(id='qinglongmon', ko='청룡몬', en='Azulongmon', grade='궁극체', tier=0, dir='qinglongmon', wiki='Qinglongmon',
      use='후보: 방울탑 전설 (칠색조 칸) — 02 34화에 나옴',
      pal=((136, 184, 240), (40, 72, 160)),
      tones=dict(white='glowing orbs, highlights', light='light blue scales', dark='dark blue scales, horns', black='eyes'),
      keep=['A long serpentine eastern dragon body coiling.', 'Antler-like horns.', 'Glowing orbs around its body.', 'Small clawed limbs.'],
      not_=['No wings.', 'Not a Western dragon.'],
      keep_back=['The coils from behind.', 'The horns.']),
 dict(id='whamon', ko='고래몬', en='Whamon', grade='완전체', tier=0, dir='whamon', wiki='Whamon',
      use='후보: 소용돌이 섬 전설 (루기아 칸) — 어드벤처 14화',
      pal=((120, 168, 232), (40, 72, 152)),
      tones=dict(white='belly', light='light blue body', dark='dark blue back', black='eyes'),
      keep=['A huge whale.', 'A wide mouth.', 'A white underside.', 'Small eyes.'],
      not_=['No legs.', 'Not a fish with scales.'],
      keep_back=['The broad back.', 'The tail.']),
]

DIGIVICE = dict(id='digivice', ko='디지바이스', en='Digivice', grade='도구', tier=1, dir='', wiki='',
                use='공박사 연구소에서 볼 대신 고르는 스타팅 선택 물건 — 롬에 넣음')

PX = {'유아기Ⅰ': 30, '유아기Ⅱ': 30, '유년기Ⅰ': 30, '유년기Ⅱ': 30, '성장기': 40}
def px(grade): return PX.get(grade, 50)

def by_id(did):
    return next((s for s in S if s['id'] == did), None)
