#include <stdint.h>
#define FONT_BANK 1
#define DATA_BANK 2
#define N_MOVES 54
#define N_FOES 34
#define N_HEROES 5
#define N_SPR 43
#define MV_STAFF 0
#define MV_STINGM 1
#define MV_PAN 2
#define MV_RING 3
#define MV_STAND 4
#define MV_SLASH 5
#define MV_STRIDER 6
#define MV_ATHELAS 7
#define MV_TORCH 8
#define MV_TWIN 9
#define MV_AIM 10
#define MV_ELFEYE 11
#define MV_KNIFE 12
#define MV_CHOP 13
#define MV_STUBBORN 14
#define MV_HEADBUTT 15
#define MV_ROAR 16
#define MV_LIGHT 17
#define MV_GLAMDRING 18
#define MV_FIRE 19
#define MV_CLEANSE 20
#define MV_BITE 21
#define MV_GROWL 22
#define MV_ROOT 23
#define MV_LULL 24
#define MV_COLD 25
#define MV_DIRGE 26
#define MV_MORGUL 27
#define MV_SHRIEK 28
#define MV_SCRATCH 29
#define MV_STRANGLE 30
#define MV_TENTACLE 31
#define MV_SPLASH 32
#define MV_RUSTY 33
#define MV_SWARM 34
#define MV_CLUB 35
#define MV_STOMP 36
#define MV_ROART 37
#define MV_WHIP 38
#define MV_FLAME 39
#define MV_WINGS 40
#define MV_CLEAVE 41
#define MV_BASH 42
#define MV_MACE 43
#define MV_WRAITHFIRE 44
#define MV_DREAD 45
#define MV_VOICE 46
#define MV_BOLT 47
#define MV_STAFFS 48
#define MV_STING 49
#define MV_WEB 50
#define MV_FANG 51
#define MV_PECK 52
#define MV_SPY 53
#define FO_DOG 0
#define FO_WILLOW 1
#define FO_WIGHT 2
#define FO_RIDER 3
#define FO_GOLLUM 4
#define FO_WATCHER 5
#define FO_GOBLIN 6
#define FO_TROLL 7
#define FO_BALROG 8
#define FO_RIDERS5 9
#define FO_WARG 10
#define FO_CREBAIN 11
#define FO_SARUMAN 12
#define FO_SHELOB 13
#define FO_WITCHKING 14
#define FO_FELLBEAST 15
#define FO_MOUTH 16
#define FO_GOLLUMB 17
#define FO_ORC 18
#define FO_MUMAK 19
#define FO_ORCT 20
#define FO_GOLLUMF 21
#define FO_SHARKEY 22
#define FO_DOGW 23
#define FO_DOGT 24
#define FO_ROOTW 25
#define FO_WIGHTW 26
#define FO_FERNYT 27
#define FO_WOLFW 28
#define FO_GOBLINW 29
#define FO_TROLLW 30
#define FO_CROWW 31
#define FO_URUKS 32
#define FO_URUK 33
#define HE_FRODOSAM 0
#define HE_ARAGORN 1
#define HE_LEGOLAS 2
#define HE_GIMLI 3
#define HE_GANDALF 4
#define SP_FRODOSAM_BACK 0
#define SP_FRODOSAM_FRONT 1
#define SP_ARAGORN_BACK 2
#define SP_ARAGORN_FRONT 3
#define SP_LEGOLAS_BACK 4
#define SP_LEGOLAS_FRONT 5
#define SP_GIMLI_BACK 6
#define SP_GIMLI_FRONT 7
#define SP_GANDALF_BACK 8
#define SP_GANDALF_FRONT 9
#define SP_DOG 10
#define SP_WILLOW 11
#define SP_WIGHT 12
#define SP_RIDER 13
#define SP_GOLLUM 14
#define SP_WATCHER 15
#define SP_GOBLIN 16
#define SP_TROLL 17
#define SP_BALROG 18
#define SP_WARG 19
#define SP_CREBAIN 20
#define SP_SARUMAN 21
#define SP_SHELOB 22
#define SP_WITCHKING 23
#define SP_FELLBEAST 24
#define SP_MOUTH 25
#define SP_ORC 26
#define SP_MUMAK 27
#define SP_SHARKEY 28
#define SP_URUK 29
#define SP_BILBO_FRONT 30
#define SP_ELROND_FRONT 31
#define SP_ARWEN_FRONT 32
#define SP_BOROMIR_FRONT 33
#define SP_MERRYPIPPIN_FRONT 34
#define SP_GALADRIEL_FRONT 35
#define SP_FARAMIR_FRONT 36
#define SP_GANDALFW_FRONT 37
#define SP_EOWYN_FRONT 38
#define SP_SAMFRODO_FRONT 39
#define SP_TOM_FRONT 40
#define SP_RING_ITEM 41
#define SP_EYE 42
#define T_0 0
#define T_1 1
#define T_2 2
#define T_3 3
#define T_4 4
#define T_5 5
#define T_6 6
enum { K_HIT, K_HEAL, K_BUFF, K_HIDE, K_DEBUFF, K_SLEEP };
enum { TY_NONE, TY_BEAST, TY_TREE, TY_WRAITH, TY_DARK, TY_ORC, TY_WIZARD };
enum { EL_NONE, EL_FIRE, EL_LIGHT, EL_ELF };
typedef struct { const char *name, *line; uint8_t pow, acc, kind, stat, elem, hits, crit, bind, weaken, amt, cure; } Move;
typedef struct { const char *name; uint8_t spr, lv; uint16_t hp; uint8_t atk, def, spd, type, boss, moves[3]; } Foe;
typedef struct { const char *name; uint8_t hp, atk, def, spd, moves[4], back, front; } Hero;
typedef struct { uint8_t bank, w, h; const uint8_t *data; } Spr;
extern const Move MOVES[]; extern const Foe FOES[]; extern const Hero HEROES[]; extern const Spr SPRS[]; extern const uint8_t EFFECT[4][7];
extern const uint16_t FONT_CP[]; extern const uint8_t FONT_GL[], FONT_GL2[]; extern const uint16_t FONT_N, FONT_SPLIT;
#define FONT_BANK2 15
