// 디지몬 자료 — 이름·등급·유형·속성·필살기는 디지몬 공식 한국어 도감(digimon.net/reference_ko)에서 그대로
// base(체력·공격·방어·스피드), exp, 진화 레벨은 게임용으로 정한 값
(function(root){root.DigiSpecies={"agumon":{"name":"아구몬","grade":"성장기","type":"파충류형","attr":"백신","sig":["베이비 플레임"],"tier":"rookie","base":[54,54,42,47],"exp":55,"evo":[{"to":"greymon","lv":10}],"src":"agumon"},
"andromon":{"name":"안드로몬","grade":"완전체","type":"사이보그형","attr":"백신","sig":["개틀링 미사일","안드로검"],"tier":"ultimate","base":[101,110,100,83],"exp":170,"evo":[],"src":"andromon"},
"angemon":{"name":"엔젤몬","grade":"성숙기","type":"천사형","attr":"백신","sig":["헤븐즈 너클"],"tier":"champion","base":[71,76,66,63],"exp":110,"evo":[{"to":"magnaangemon","lv":28,"need":"희망"}],"src":"angemon"},
"angewomon":{"name":"엔젤우몬","grade":"완전체","type":"대천사형","attr":"백신","sig":["천국의 화살","천국의 미소"],"tier":"ultimate","base":[96,100,92,83],"exp":170,"evo":[],"src":"angewomon"},
"apocalymon":{"name":"아포카리몬","grade":"궁극체","type":"종족불명","attr":"불명","sig":["다크니스 존"],"tier":"mega","base":[112,129,115,108],"exp":230,"evo":[],"src":"apoclymon"},
"birdramon":{"name":"버드라몬","grade":"성숙기","type":"거조형","attr":"백신","sig":["메테오 윙"],"tier":"champion","base":[70,80,65,73],"exp":110,"evo":[{"to":"garudamon","lv":28,"need":"사랑"}],"src":"birdramon"},
"botamon":{"name":"깜몬","grade":"유아기Ⅰ","type":"슬라임형","attr":"없음","sig":["산성 거품"],"tier":"baby","base":[31,22,18,23],"exp":20,"evo":[{"to":"koromon","lv":4}],"src":"botamon"},
"centarumon":{"name":"켄터스몬","grade":"성숙기","type":"수인형","attr":"데이터","sig":["헌팅 캐논"],"tier":"champion","base":[72,74,71,64],"exp":110,"evo":[],"src":"centalmon"},
"cockatrimon":{"name":"꼬끼몬","grade":"성숙기","type":"거조형","attr":"데이터","sig":["페트라 파이어"],"tier":"champion","base":[76,77,64,64],"exp":110,"evo":[],"src":"cockatrimon"},
"devimon":{"name":"데블몬","grade":"성숙기","type":"타천사형","attr":"바이러스","sig":["데스 크로우"],"tier":"champion","base":[79,88,66,71],"exp":110,"evo":[],"src":"devimon"},
"digitamamon":{"name":"디지타몬","grade":"완전체","type":"퍼펙트형","attr":"데이터","sig":["에니그마","나이트메어 신드롬"],"tier":"ultimate","base":[89,97,86,84],"exp":170,"evo":[],"src":"digitamamon"},
"drimogemon":{"name":"두리몬","grade":"성숙기","type":"짐승형","attr":"데이터","sig":["드릴 스핀","크러셔 본"],"tier":"champion","base":[70,82,71,64],"exp":110,"evo":[],"src":"drimogemon"},
"elecmon":{"name":"에렉몬","grade":"성장기","type":"포유류형","attr":"데이터","sig":["날벼락치기"],"tier":"rookie","base":[43,50,39,57],"exp":55,"evo":[],"src":"elecmon"},
"etemon":{"name":"에테몬","grade":"완전체","type":"퍼펫형","attr":"바이러스","sig":["러브 세레나데","다크 스피릿츠"],"tier":"ultimate","base":[88,96,87,83],"exp":170,"evo":[],"src":"etemon"},
"gabumon":{"name":"파피몬","grade":"성장기","type":"파충류형","attr":"데이터","sig":["쁘띠 파이어"],"tier":"rookie","base":[53,49,43,47],"exp":55,"evo":[{"to":"garurumon","lv":10}],"src":"gabumon"},
"garudamon":{"name":"가루다몬","grade":"완전체","type":"조인형","attr":"백신","sig":["섀도 윙"],"tier":"ultimate","base":[92,98,91,83],"exp":170,"evo":[],"src":"garudamon"},
"garurumon":{"name":"가루몬","grade":"성숙기","type":"짐승형","attr":"백신","sig":["푸른화염포"],"tier":"champion","base":[70,85,68,73],"exp":110,"evo":[{"to":"weregarurumon","lv":28,"need":"우정"}],"src":"garurumon"},
"gekomon":{"name":"개굴몬","grade":"성숙기","type":"양서류형","attr":"바이러스","sig":["크래시 심포니"],"tier":"champion","base":[73,78,66,63],"exp":110,"evo":[],"src":"gekomon"},
"gomamon":{"name":"쉬라몬","grade":"성장기","type":"바다짐승형","attr":"백신","sig":["물고기 행진"],"tier":"rookie","base":[49,49,43,47],"exp":55,"evo":[{"to":"ikkakumon","lv":10}],"src":"gomamon"},
"greymon":{"name":"그레이몬","grade":"성숙기","type":"공룡형","attr":"백신","sig":["메가파이어"],"tier":"champion","base":[76,88,69,61],"exp":110,"evo":[{"to":"metalgreymon","lv":28,"need":"용기"}],"src":"greymon-first"},
"magnaangemon":{"name":"홀리엔젤몬","grade":"완전체","type":"대천사형","attr":"백신","sig":["천국의 문"],"tier":"ultimate","base":[94,100,87,84],"exp":170,"evo":[],"src":"holyangemon"},
"ikkakumon":{"name":"원뿔몬","grade":"성숙기","type":"바다짐승형","attr":"백신","sig":["뿔 날리기"],"tier":"champion","base":[75,78,70,63],"exp":110,"evo":[{"to":"zudomon","lv":28,"need":"성실"}],"src":"ikkakumon"},
"kabuterimon":{"name":"캅테리몬","grade":"성숙기","type":"곤충형","attr":"백신","sig":["전기충격"],"tier":"champion","base":[74,78,64,64],"exp":110,"evo":[],"src":"kabuterimon"},
"kiwimon":{"name":"키위몬","grade":"성숙기","type":"고대새형","attr":"데이터","sig":["꼬마 키위탄"],"tier":"champion","base":[69,79,66,63],"exp":110,"evo":[],"src":"kiwimon"},
"koromon":{"name":"코로몬","grade":"유년기Ⅱ","type":"렛서형","attr":"없음","sig":["거품"],"tier":"baby2","base":[44,34,29,31],"exp":35,"evo":[{"to":"agumon","lv":8}],"src":"koromon"},
"kuwagamon":{"name":"쿠가몬","grade":"성숙기","type":"곤충형","attr":"바이러스","sig":["시저 암즈"],"tier":"champion","base":[75,90,70,67],"exp":110,"evo":[],"src":"kuwagamon"},
"leomon":{"name":"레오몬","grade":"성숙기","type":"수인형","attr":"백신","sig":["수왕권"],"tier":"champion","base":[74,84,65,69],"exp":110,"evo":[],"src":"leomon"},
"lilimon":{"name":"릴리몬","grade":"완전체","type":"요정형","attr":"데이터","sig":["꽃잎 포"],"tier":"ultimate","base":[88,100,88,83],"exp":170,"evo":[],"src":"lilimon"},
"mamemon":{"name":"콩알몬","grade":"완전체","type":"돌연변이형","attr":"데이터","sig":["스마일리 봄"],"tier":"ultimate","base":[96,99,88,83],"exp":170,"evo":[],"src":"mamemon"},
"meramon":{"name":"메라몬","grade":"성숙기","type":"화염형","attr":"데이터","sig":["불타는 주먹"],"tier":"champion","base":[72,87,62,67],"exp":110,"evo":[],"src":"meramon"},
"metalgarurumon":{"name":"메탈가루몬","grade":"궁극체","type":"사이보그형","attr":"데이터","sig":["코큐토스 브레스","가루 토마호크","그레이스 크로스 프리저"],"tier":"mega","base":[110,122,113,108],"exp":230,"evo":[],"src":"metalgarurumon"},
"metalgreymon":{"name":"메탈그레이몬(백신종)","grade":"완전체","type":"사이보그형","attr":"백신","sig":["트라이던트 암","기가 디스트로이어","지가 스톰"],"tier":"ultimate","base":[92,96,88,84],"exp":170,"evo":[{"to":"wargreymon","lv":45,"need":"event"}],"src":"metalgreymon-v"},
"metalseadramon":{"name":"메탈시드라몬","grade":"궁극체","type":"사이보그형","attr":"데이터","sig":["얼티메이트 스트림"],"tier":"mega","base":[108,126,113,108],"exp":230,"evo":[],"src":"metalseadramon"},
"mochimon":{"name":"모티몬","grade":"유년기Ⅱ","type":"렛서형","attr":"없음","sig":["신축성 거품"],"tier":"baby2","base":[39,36,30,31],"exp":35,"evo":[{"to":"tentomon","lv":8}],"src":"mochimon"},
"monochromon":{"name":"모노크로몬","grade":"성숙기","type":"갑룡형","attr":"데이터","sig":["볼케이노 스트라이크"],"tier":"champion","base":[78,83,80,54],"exp":110,"evo":[],"src":"monochromon"},
"monzaemon":{"name":"퍼펫몬","grade":"완전체","type":"퍼펫형","attr":"백신","sig":["러블리 어택"],"tier":"ultimate","base":[96,101,92,83],"exp":170,"evo":[],"src":"monzaemon"},
"machinedramon":{"name":"파워드라몬","grade":"궁극체","type":"머신형","attr":"바이러스","sig":["∞캐논"],"tier":"mega","base":[115,129,111,108],"exp":230,"evo":[],"src":"mugendramon"},
"nanimon":{"name":"모야몬","grade":"성숙기","type":"인베이드형","attr":"바이러스","sig":["응가","응가 덩크"],"tier":"champion","base":[73,78,66,63],"exp":110,"evo":[],"src":"nanimon"},
"numemon":{"name":"워매몬","grade":"성숙기","type":"연체형","attr":"바이러스","sig":["응가 투척"],"tier":"champion","base":[80,69,60,63],"exp":110,"evo":[],"src":"numemon"},
"nyaromon":{"name":"야옹몬","grade":"유년기Ⅱ","type":"렛서형","attr":"없음","sig":["폭스 테일"],"tier":"baby2","base":[37,30,30,31],"exp":35,"evo":[{"to":"salamon","lv":8}],"src":"nyaromon"},
"ogremon":{"name":"우가몬","grade":"성숙기","type":"귀인형","attr":"바이러스","sig":["패왕권"],"tier":"champion","base":[71,78,66,63],"exp":110,"evo":[],"src":"orgemon"},
"palmon":{"name":"팔몬","grade":"성장기","type":"식물형","attr":"데이터","sig":["포이즌 아이비"],"tier":"rookie","base":[54,54,42,47],"exp":55,"evo":[{"to":"togemon","lv":10}],"src":"palmon"},
"patamon":{"name":"파닥몬","grade":"성장기","type":"포유류형","attr":"데이터","sig":["공기 팡","날개 따귀 때리기"],"tier":"rookie","base":[51,50,43,47],"exp":55,"evo":[{"to":"angemon","lv":10}],"src":"patamon"},
"picodevimon":{"name":"피코데블몬","grade":"성장기","type":"소악마형","attr":"바이러스","sig":["피코 주사기"],"tier":"rookie","base":[42,53,35,60],"exp":55,"evo":[],"src":"picodevimon"},
"piedmon":{"name":"피에몬","grade":"궁극체","type":"마인형","attr":"바이러스","sig":["트럼프검"],"tier":"mega","base":[109,124,110,107],"exp":230,"evo":[],"src":"piemon"},
"pinochimon":{"name":"피노키몬","grade":"궁극체","type":"퍼펫형","attr":"바이러스","sig":["피노키해머"],"tier":"mega","base":[113,129,115,108],"exp":230,"evo":[],"src":"pinochimon"},
"piyomon":{"name":"피요몬","grade":"성장기","type":"병아리형","attr":"백신","sig":["빙빙회오리"],"tier":"rookie","base":[51,53,44,47],"exp":55,"evo":[{"to":"birdramon","lv":10}],"src":"piyomon"},
"salamon":{"name":"플롯트몬","grade":"성장기","type":"포유류형","attr":"백신","sig":["플롯트의 외침"],"tier":"rookie","base":[46,49,43,47],"exp":55,"evo":[{"to":"gatomon","lv":10}],"src":"plotmon"},
"punimon":{"name":"푸니몬","grade":"유아기Ⅰ","type":"슬라임형","attr":"없음","sig":["산성 거품"],"tier":"baby","base":[26,24,19,23],"exp":20,"evo":[{"to":"tsunomon","lv":4}],"src":"punimon"},
"seadramon":{"name":"시드라몬","grade":"성숙기","type":"수생형","attr":"데이터","sig":["얼음 화살"],"tier":"champion","base":[68,76,69,63],"exp":110,"evo":[],"src":"seadramon"},
"shellmon":{"name":"쉘몬","grade":"성숙기","type":"연체형","attr":"데이터","sig":["하이드로 프레셔"],"tier":"champion","base":[80,74,90,47],"exp":110,"evo":[],"src":"shellmon"},
"gatomon":{"name":"가트몬","grade":"성숙기","type":"성수형","attr":"백신","sig":["고양이 펀치","최면술"],"tier":"champion","base":[69,78,66,63],"exp":110,"evo":[{"to":"angewomon","lv":28,"need":"빛"}],"src":"tailmon"},
"tanemon":{"name":"시드몬","grade":"유년기Ⅱ","type":"알뿌리형","attr":"없음","sig":["점성 거품"],"tier":"baby2","base":[43,32,28,31],"exp":35,"evo":[{"to":"palmon","lv":8}],"src":"tanemon"},
"tentomon":{"name":"텐타몬","grade":"성장기","type":"곤충형","attr":"백신","sig":["쁘띠 썬더"],"tier":"rookie","base":[48,48,45,47],"exp":55,"evo":[{"to":"kabuterimon","lv":10}],"src":"tentomon"},
"togemon":{"name":"니드몬","grade":"성숙기","type":"식물형","attr":"데이터","sig":["바늘 뿜기"],"tier":"champion","base":[73,79,66,63],"exp":110,"evo":[{"to":"lilimon","lv":28,"need":"순수"}],"src":"togemon"},
"tokomon":{"name":"토코몬","grade":"유년기Ⅱ","type":"렛서형","attr":"없음","sig":["물어뜯기"],"tier":"baby2","base":[37,34,29,31],"exp":35,"evo":[{"to":"patamon","lv":8}],"src":"tokomon"},
"tonosamagekomon":{"name":"왕개굴몬","grade":"완전체","type":"양서류형","attr":"바이러스","sig":["사무라이 톤"],"tier":"ultimate","base":[95,100,93,85],"exp":170,"evo":[],"src":"tonosamagekomon"},
"tsunomon":{"name":"뿔몬","grade":"유년기Ⅱ","type":"렛서형","attr":"없음","sig":["산성 거품"],"tier":"baby2","base":[44,32,31,31],"exp":35,"evo":[{"to":"gabumon","lv":8}],"src":"tunomon"},
"tyranomon":{"name":"티라노몬","grade":"성숙기","type":"공룡형","attr":"데이터","sig":["불 뿜기"],"tier":"champion","base":[76,89,74,55],"exp":110,"evo":[],"src":"tyranomon"},
"myotismon":{"name":"묘티스몬","grade":"완전체","type":"언데드형","attr":"바이러스","sig":["나이트 레이드"],"tier":"ultimate","base":[96,104,92,83],"exp":170,"evo":[],"src":"vamdemon"},
"vegimon":{"name":"베지몬","grade":"성숙기","type":"식충식물형","attr":"바이러스","sig":["응가 투척"],"tier":"champion","base":[69,78,66,63],"exp":110,"evo":[],"src":"vegimon"},
"wargreymon":{"name":"워그레이몬","grade":"궁극체","type":"용인형","attr":"백신","sig":["가이아 포스","브레이브 토네이도"],"tier":"mega","base":[109,123,116,108],"exp":230,"evo":[],"src":"wargreymon"},
"weregarurumon":{"name":"워가루몬","grade":"완전체","type":"수인형","attr":"백신","sig":["카이저 네일"],"tier":"ultimate","base":[93,103,90,84],"exp":170,"evo":[{"to":"metalgarurumon","lv":45,"need":"event"}],"src":"weregarrumon"},
"wizardmon":{"name":"위자몬","grade":"성숙기","type":"마인형","attr":"데이터","sig":["번쩍 구름"],"tier":"champion","base":[74,80,70,63],"exp":110,"evo":[],"src":"wizarmon"},
"frigimon":{"name":"프리지몬","grade":"성숙기","type":"빙설형","attr":"백신","sig":["절대 영도 펀치"],"tier":"champion","base":[82,82,78,51],"exp":110,"evo":[],"src":"yukidarumon"},
"zudomon":{"name":"쥬드몬","grade":"완전체","type":"바다짐승형","attr":"백신","sig":["해머 스파크"],"tier":"ultimate","base":[94,103,89,83],"exp":170,"evo":[],"src":"zudomon"},
"bukamon":{"name":"둥실몬","grade":"유년기Ⅱ","type":"렛서형","attr":"없음","sig":["공기 거품"],"tier":"baby2","base":[38,31,28,31],"exp":35,"evo":[{"to":"gomamon","lv":8}],"src":"pukamon"},
"pyocomon":{"name":"어니몬","grade":"유년기Ⅱ","type":"알뿌리형","attr":"없음","sig":["샤본 플라워"],"tier":"baby2","base":[38,30,30,31],"exp":35,"evo":[{"to":"piyomon","lv":8}],"src":"pyocomon"}};
root.DigiPower={"baby": 25, "baby2": 35, "rookie": 50, "champion": 75, "ultimate": 95, "mega": 120};})(typeof window!=="undefined"?window:globalThis);
